// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockauthOTP is an autogenerated mock type for the authOTP type
type MockauthOTP struct {
	mock.Mock
}

type MockauthOTP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockauthOTP) EXPECT() *MockauthOTP_Expecter {
	return &MockauthOTP_Expecter{mock: &_m.Mock}
}

// VerifyOTP provides a mock function with given fields: ctx, email, code, mode
func (_m *MockauthOTP) VerifyOTP(ctx context.Context, email string, code string, mode string) error {
	ret := _m.Called(ctx, email, code, mode)

	if len(ret) == 0 {
		panic("no return value specified for VerifyOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, email, code, mode)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockauthOTP_VerifyOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyOTP'
type MockauthOTP_VerifyOTP_Call struct {
	*mock.Call
}

// VerifyOTP is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - code string
//   - mode string
func (_e *MockauthOTP_Expecter) VerifyOTP(ctx interface{}, email interface{}, code interface{}, mode interface{}) *MockauthOTP_VerifyOTP_Call {
	return &MockauthOTP_VerifyOTP_Call{Call: _e.mock.On("VerifyOTP", ctx, email, code, mode)}
}

func (_c *MockauthOTP_VerifyOTP_Call) Run(run func(ctx context.Context, email string, code string, mode string)) *MockauthOTP_VerifyOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockauthOTP_VerifyOTP_Call) Return(_a0 error) *MockauthOTP_VerifyOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockauthOTP_VerifyOTP_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockauthOTP_VerifyOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockauthOTP creates a new instance of MockauthOTP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockauthOTP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockauthOTP {
	mock := &MockauthOTP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
