// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthStorage is an autogenerated mock type for the AuthStorage type
type MockAuthStorage struct {
	mock.Mock
}

type MockAuthStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthStorage) EXPECT() *MockAuthStorage_Expecter {
	return &MockAuthStorage_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: _a0
func (_m *MockAuthStorage) Download(_a0 string) ([]byte, string, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuthStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockAuthStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - _a0 string
func (_e *MockAuthStorage_Expecter) Download(_a0 interface{}) *MockAuthStorage_Download_Call {
	return &MockAuthStorage_Download_Call{Call: _e.mock.On("Download", _a0)}
}

func (_c *MockAuthStorage_Download_Call) Run(run func(_a0 string)) *MockAuthStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthStorage_Download_Call) Return(_a0 []byte, _a1 string, _a2 error) *MockAuthStorage_Download_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuthStorage_Download_Call) RunAndReturn(run func(string) ([]byte, string, error)) *MockAuthStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicURL provides a mock function with given fields: _a0
func (_m *MockAuthStorage) GetPublicURL(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAuthStorage_GetPublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicURL'
type MockAuthStorage_GetPublicURL_Call struct {
	*mock.Call
}

// GetPublicURL is a helper method to define mock.On call
//   - _a0 string
func (_e *MockAuthStorage_Expecter) GetPublicURL(_a0 interface{}) *MockAuthStorage_GetPublicURL_Call {
	return &MockAuthStorage_GetPublicURL_Call{Call: _e.mock.On("GetPublicURL", _a0)}
}

func (_c *MockAuthStorage_GetPublicURL_Call) Run(run func(_a0 string)) *MockAuthStorage_GetPublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthStorage_GetPublicURL_Call) Return(_a0 string) *MockAuthStorage_GetPublicURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthStorage_GetPublicURL_Call) RunAndReturn(run func(string) string) *MockAuthStorage_GetPublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// StoreFromReader provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockAuthStorage) StoreFromReader(_a0 io.Reader, _a1 string, _a2 string, _a3 bool) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for StoreFromReader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Reader, string, string, bool) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthStorage_StoreFromReader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StoreFromReader'
type MockAuthStorage_StoreFromReader_Call struct {
	*mock.Call
}

// StoreFromReader is a helper method to define mock.On call
//   - _a0 io.Reader
//   - _a1 string
//   - _a2 string
//   - _a3 bool
func (_e *MockAuthStorage_Expecter) StoreFromReader(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockAuthStorage_StoreFromReader_Call {
	return &MockAuthStorage_StoreFromReader_Call{Call: _e.mock.On("StoreFromReader", _a0, _a1, _a2, _a3)}
}

func (_c *MockAuthStorage_StoreFromReader_Call) Run(run func(_a0 io.Reader, _a1 string, _a2 string, _a3 bool)) *MockAuthStorage_StoreFromReader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader), args[1].(string), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockAuthStorage_StoreFromReader_Call) Return(_a0 error) *MockAuthStorage_StoreFromReader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthStorage_StoreFromReader_Call) RunAndReturn(run func(io.Reader, string, string, bool) error) *MockAuthStorage_StoreFromReader_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthStorage creates a new instance of MockAuthStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthStorage {
	mock := &MockAuthStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
