// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	adapter "AtoiTalkAPI/internal/adapter"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockMediaStorage is an autogenerated mock type for the MediaStorage type
type MockMediaStorage struct {
	mock.Mock
}

type MockMediaStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaStorage) EXPECT() *MockMediaStorage_Expecter {
	return &MockMediaStorage_Expecter{mock: &_m.Mock}
}

// GetPresignedPutURL provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockMediaStorage) GetPresignedPutURL(_a0 string, _a1 string, _a2 int64, _a3 bool, _a4 time.Duration) (string, map[string]string, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedPutURL")
	}

	var r0 string
	var r1 map[string]string
	var r2 error
	if rf, ok := ret.Get(0).(func(string, string, int64, bool, time.Duration) (string, map[string]string, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(string, string, int64, bool, time.Duration) string); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, int64, bool, time.Duration) map[string]string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(map[string]string)
		}
	}

	if rf, ok := ret.Get(2).(func(string, string, int64, bool, time.Duration) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockMediaStorage_GetPresignedPutURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedPutURL'
type MockMediaStorage_GetPresignedPutURL_Call struct {
	*mock.Call
}

// GetPresignedPutURL is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
//   - _a2 int64
//   - _a3 bool
//   - _a4 time.Duration
func (_e *MockMediaStorage_Expecter) GetPresignedPutURL(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockMediaStorage_GetPresignedPutURL_Call {
	return &MockMediaStorage_GetPresignedPutURL_Call{Call: _e.mock.On("GetPresignedPutURL", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockMediaStorage_GetPresignedPutURL_Call) Run(run func(_a0 string, _a1 string, _a2 int64, _a3 bool, _a4 time.Duration)) *MockMediaStorage_GetPresignedPutURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(int64), args[3].(bool), args[4].(time.Duration))
	})
	return _c
}

func (_c *MockMediaStorage_GetPresignedPutURL_Call) Return(_a0 string, _a1 map[string]string, _a2 error) *MockMediaStorage_GetPresignedPutURL_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockMediaStorage_GetPresignedPutURL_Call) RunAndReturn(run func(string, string, int64, bool, time.Duration) (string, map[string]string, error)) *MockMediaStorage_GetPresignedPutURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPresignedURL provides a mock function with given fields: _a0, _a1
func (_m *MockMediaStorage) GetPresignedURL(_a0 string, _a1 time.Duration) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaStorage_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MockMediaStorage_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - _a0 string
//   - _a1 time.Duration
func (_e *MockMediaStorage_Expecter) GetPresignedURL(_a0 interface{}, _a1 interface{}) *MockMediaStorage_GetPresignedURL_Call {
	return &MockMediaStorage_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", _a0, _a1)}
}

func (_c *MockMediaStorage_GetPresignedURL_Call) Run(run func(_a0 string, _a1 time.Duration)) *MockMediaStorage_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockMediaStorage_GetPresignedURL_Call) Return(_a0 string, _a1 error) *MockMediaStorage_GetPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaStorage_GetPresignedURL_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *MockMediaStorage_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicURL provides a mock function with given fields: _a0
func (_m *MockMediaStorage) GetPublicURL(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockMediaStorage_GetPublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicURL'
type MockMediaStorage_GetPublicURL_Call struct {
	*mock.Call
}

// GetPublicURL is a helper method to define mock.On call
//   - _a0 string
func (_e *MockMediaStorage_Expecter) GetPublicURL(_a0 interface{}) *MockMediaStorage_GetPublicURL_Call {
	return &MockMediaStorage_GetPublicURL_Call{Call: _e.mock.On("GetPublicURL", _a0)}
}

func (_c *MockMediaStorage_GetPublicURL_Call) Run(run func(_a0 string)) *MockMediaStorage_GetPublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockMediaStorage_GetPublicURL_Call) Return(_a0 string) *MockMediaStorage_GetPublicURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMediaStorage_GetPublicURL_Call) RunAndReturn(run func(string) string) *MockMediaStorage_GetPublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// Head provides a mock function with given fields: _a0, _a1
func (_m *MockMediaStorage) Head(_a0 string, _a1 bool) (*adapter.StorageObjectInfo, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Head")
	}

	var r0 *adapter.StorageObjectInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(string, bool) (*adapter.StorageObjectInfo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, bool) *adapter.StorageObjectInfo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*adapter.StorageObjectInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(string, bool) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaStorage_Head_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Head'
type MockMediaStorage_Head_Call struct {
	*mock.Call
}

// Head is a helper method to define mock.On call
//   - _a0 string
//   - _a1 bool
func (_e *MockMediaStorage_Expecter) Head(_a0 interface{}, _a1 interface{}) *MockMediaStorage_Head_Call {
	return &MockMediaStorage_Head_Call{Call: _e.mock.On("Head", _a0, _a1)}
}

func (_c *MockMediaStorage_Head_Call) Run(run func(_a0 string, _a1 bool)) *MockMediaStorage_Head_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockMediaStorage_Head_Call) Return(_a0 *adapter.StorageObjectInfo, _a1 error) *MockMediaStorage_Head_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaStorage_Head_Call) RunAndReturn(run func(string, bool) (*adapter.StorageObjectInfo, error)) *MockMediaStorage_Head_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaStorage creates a new instance of MockMediaStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaStorage {
	mock := &MockMediaStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
