// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisPresence is an autogenerated mock type for the RedisPresence type
type MockRedisPresence struct {
	mock.Mock
}

type MockRedisPresence_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisPresence) EXPECT() *MockRedisPresence_Expecter {
	return &MockRedisPresence_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: _a0, _a1
func (_m *MockRedisPresence) Exists(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisPresence_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRedisPresence_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRedisPresence_Expecter) Exists(_a0 interface{}, _a1 interface{}) *MockRedisPresence_Exists_Call {
	return &MockRedisPresence_Exists_Call{Call: _e.mock.On("Exists", _a0, _a1)}
}

func (_c *MockRedisPresence_Exists_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRedisPresence_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisPresence_Exists_Call) Return(_a0 bool, _a1 error) *MockRedisPresence_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisPresence_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRedisPresence_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisPresence creates a new instance of MockRedisPresence. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisPresence(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisPresence {
	mock := &MockRedisPresence{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
