// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisOAuthStore is an autogenerated mock type for the RedisOAuthStore type
type MockRedisOAuthStore struct {
	mock.Mock
}

type MockRedisOAuthStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisOAuthStore) EXPECT() *MockRedisOAuthStore_Expecter {
	return &MockRedisOAuthStore_Expecter{mock: &_m.Mock}
}

// GetDel provides a mock function with given fields: _a0, _a1
func (_m *MockRedisOAuthStore) GetDel(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetDel")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisOAuthStore_GetDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDel'
type MockRedisOAuthStore_GetDel_Call struct {
	*mock.Call
}

// GetDel is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRedisOAuthStore_Expecter) GetDel(_a0 interface{}, _a1 interface{}) *MockRedisOAuthStore_GetDel_Call {
	return &MockRedisOAuthStore_GetDel_Call{Call: _e.mock.On("GetDel", _a0, _a1)}
}

func (_c *MockRedisOAuthStore_GetDel_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRedisOAuthStore_GetDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisOAuthStore_GetDel_Call) Return(_a0 string, _a1 error) *MockRedisOAuthStore_GetDel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisOAuthStore_GetDel_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRedisOAuthStore_GetDel_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockRedisOAuthStore) Set(_a0 context.Context, _a1 string, _a2 interface{}, _a3 time.Duration) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisOAuthStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisOAuthStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 interface{}
//   - _a3 time.Duration
func (_e *MockRedisOAuthStore_Expecter) Set(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockRedisOAuthStore_Set_Call {
	return &MockRedisOAuthStore_Set_Call{Call: _e.mock.On("Set", _a0, _a1, _a2, _a3)}
}

func (_c *MockRedisOAuthStore_Set_Call) Run(run func(_a0 context.Context, _a1 string, _a2 interface{}, _a3 time.Duration)) *MockRedisOAuthStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRedisOAuthStore_Set_Call) Return(_a0 error) *MockRedisOAuthStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisOAuthStore_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockRedisOAuthStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisOAuthStore creates a new instance of MockRedisOAuthStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisOAuthStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisOAuthStore {
	mock := &MockRedisOAuthStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
