// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisOnlineStore is an autogenerated mock type for the RedisOnlineStore type
type MockRedisOnlineStore struct {
	mock.Mock
}

type MockRedisOnlineStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisOnlineStore) EXPECT() *MockRedisOnlineStore_Expecter {
	return &MockRedisOnlineStore_Expecter{mock: &_m.Mock}
}

// Exists provides a mock function with given fields: _a0, _a1
func (_m *MockRedisOnlineStore) Exists(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisOnlineStore_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockRedisOnlineStore_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRedisOnlineStore_Expecter) Exists(_a0 interface{}, _a1 interface{}) *MockRedisOnlineStore_Exists_Call {
	return &MockRedisOnlineStore_Exists_Call{Call: _e.mock.On("Exists", _a0, _a1)}
}

func (_c *MockRedisOnlineStore_Exists_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRedisOnlineStore_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisOnlineStore_Exists_Call) Return(_a0 bool, _a1 error) *MockRedisOnlineStore_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisOnlineStore_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRedisOnlineStore_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsMany provides a mock function with given fields: _a0, _a1
func (_m *MockRedisOnlineStore) ExistsMany(_a0 context.Context, _a1 []string) (map[string]bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ExistsMany")
	}

	var r0 map[string]bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]bool)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisOnlineStore_ExistsMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsMany'
type MockRedisOnlineStore_ExistsMany_Call struct {
	*mock.Call
}

// ExistsMany is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 []string
func (_e *MockRedisOnlineStore_Expecter) ExistsMany(_a0 interface{}, _a1 interface{}) *MockRedisOnlineStore_ExistsMany_Call {
	return &MockRedisOnlineStore_ExistsMany_Call{Call: _e.mock.On("ExistsMany", _a0, _a1)}
}

func (_c *MockRedisOnlineStore_ExistsMany_Call) Run(run func(_a0 context.Context, _a1 []string)) *MockRedisOnlineStore_ExistsMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRedisOnlineStore_ExistsMany_Call) Return(_a0 map[string]bool, _a1 error) *MockRedisOnlineStore_ExistsMany_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisOnlineStore_ExistsMany_Call) RunAndReturn(run func(context.Context, []string) (map[string]bool, error)) *MockRedisOnlineStore_ExistsMany_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisOnlineStore creates a new instance of MockRedisOnlineStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisOnlineStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisOnlineStore {
	mock := &MockRedisOnlineStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
