version: false
with-expecter: true
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
filename: "{{.InterfaceName | snakecase}}.go"
mockname: "Mock{{.InterfaceName}}"
packages:
  AtoiTalkAPI/internal/infrastructure/captcha:
    interfaces:
      Verifier: {}
    config:
      dir: "internal/infrastructure/mocks"
      outpkg: mocks
      mockname: "Mock{{.InterfaceName}}"
  AtoiTalkAPI/internal/infrastructure/email:
    interfaces:
      Sender: {}
    config:
      dir: "internal/infrastructure/mocks"
      outpkg: mocks
      mockname: "Mock{{.InterfaceName}}"
  AtoiTalkAPI/internal/infrastructure/object_storage:
    interfaces:
      PublicURLGenerator: {}
      AuthStorage: {}
      MediaStorage: {}
      URLGenerator: {}
    config:
      dir: "internal/infrastructure/mocks"
      outpkg: mocks
      mockname: "Mock{{.InterfaceName}}"
  AtoiTalkAPI/internal/infrastructure/redis:
    interfaces:
      Store: {}
      OAuthStore: {}
      Presence: {}
      OnlineStore: {}
      Cache: {}
    config:
      dir: "internal/infrastructure/mocks"
      outpkg: mocks
      mockname: "Mock{{.InterfaceName}}"
  AtoiTalkAPI/internal/infrastructure/database/repository:
    interfaces:
      UserReader: {}
      SessionStore: {}
      RateLimiter: {}
      TokenBlacklistStore: {}
      ChatReader: {}
      GroupMemberReader: {}
      GroupChatReader: {}
      MessageReader: {}
    config:
      dir: "internal/infrastructure/database/repository/mocks"
      outpkg: mocks
      mockname: "Mock{{.InterfaceName}}"
  AtoiTalkAPI/internal/api/application:
    interfaces:
      authOTP: {}
      AuthVerifier: {}
      ChatServicePort: {}
      AuthServicePort: {}
      AccountServicePort: {}
      OTPServicePort: {}
      UserServicePort: {}
      PrivateChatServicePort: {}
      GroupChatServicePort: {}
      MessageServicePort: {}
      MediaServicePort: {}
      ReportServicePort: {}
      AdminServicePort: {}
  AtoiTalkAPI/internal/messaging/events:
    interfaces:
      Publisher: {}
    config:
      dir: "{{.InterfaceDir}}/mocks"
      outpkg: mocks
      mockname: "Mock{{.InterfaceName}}"
