// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ent "AtoiTalkAPI/ent"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGroupMemberReader is an autogenerated mock type for the GroupMemberReader type
type MockGroupMemberReader struct {
	mock.Mock
}

type MockGroupMemberReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupMemberReader) EXPECT() *MockGroupMemberReader_Expecter {
	return &MockGroupMemberReader_Expecter{mock: &_m.Mock}
}

// CountActiveMembersByGroupIDs provides a mock function with given fields: _a0, _a1
func (_m *MockGroupMemberReader) CountActiveMembersByGroupIDs(_a0 context.Context, _a1 ...uuid.UUID) (map[uuid.UUID]int, error) {
	_va := make([]interface{}, len(_a1))
	for _i := range _a1 {
		_va[_i] = _a1[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveMembersByGroupIDs")
	}

	var r0 map[uuid.UUID]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) (map[uuid.UUID]int, error)); ok {
		return rf(_a0, _a1...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...uuid.UUID) map[uuid.UUID]int); ok {
		r0 = rf(_a0, _a1...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...uuid.UUID) error); ok {
		r1 = rf(_a0, _a1...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupMemberReader_CountActiveMembersByGroupIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveMembersByGroupIDs'
type MockGroupMemberReader_CountActiveMembersByGroupIDs_Call struct {
	*mock.Call
}

// CountActiveMembersByGroupIDs is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 ...uuid.UUID
func (_e *MockGroupMemberReader_Expecter) CountActiveMembersByGroupIDs(_a0 interface{}, _a1 ...interface{}) *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call {
	return &MockGroupMemberReader_CountActiveMembersByGroupIDs_Call{Call: _e.mock.On("CountActiveMembersByGroupIDs",
		append([]interface{}{_a0}, _a1...)...)}
}

func (_c *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call) Run(run func(_a0 context.Context, _a1 ...uuid.UUID)) *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]uuid.UUID, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(uuid.UUID)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call) Return(_a0 map[uuid.UUID]int, _a1 error) *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call) RunAndReturn(run func(context.Context, ...uuid.UUID) (map[uuid.UUID]int, error)) *MockGroupMemberReader_CountActiveMembersByGroupIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SearchGroupMembers provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockGroupMemberReader) SearchGroupMembers(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int) ([]*ent.GroupMember, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for SearchGroupMembers")
	}

	var r0 []*ent.GroupMember
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) ([]*ent.GroupMember, string, bool, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) []*ent.GroupMember); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.GroupMember)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, string, int) bool); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, string, string, int) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockGroupMemberReader_SearchGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchGroupMembers'
type MockGroupMemberReader_SearchGroupMembers_Call struct {
	*mock.Call
}

// SearchGroupMembers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
//   - _a3 string
//   - _a4 int
func (_e *MockGroupMemberReader_Expecter) SearchGroupMembers(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockGroupMemberReader_SearchGroupMembers_Call {
	return &MockGroupMemberReader_SearchGroupMembers_Call{Call: _e.mock.On("SearchGroupMembers", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockGroupMemberReader_SearchGroupMembers_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int)) *MockGroupMemberReader_SearchGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockGroupMemberReader_SearchGroupMembers_Call) Return(_a0 []*ent.GroupMember, _a1 string, _a2 bool, _a3 error) *MockGroupMemberReader_SearchGroupMembers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockGroupMemberReader_SearchGroupMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, int) ([]*ent.GroupMember, string, bool, error)) *MockGroupMemberReader_SearchGroupMembers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupMemberReader creates a new instance of MockGroupMemberReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupMemberReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupMemberReader {
	mock := &MockGroupMemberReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
