// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ent "AtoiTalkAPI/ent"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockMessageReader is an autogenerated mock type for the MessageReader type
type MockMessageReader struct {
	mock.Mock
}

type MockMessageReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageReader) EXPECT() *MockMessageReader_Expecter {
	return &MockMessageReader_Expecter{mock: &_m.Mock}
}

// GetMessages provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5
func (_m *MockMessageReader) GetMessages(_a0 context.Context, _a1 uuid.UUID, _a2 *time.Time, _a3 uuid.UUID, _a4 int, _a5 string) ([]*ent.Message, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []*ent.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int, string) ([]*ent.Message, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4, _a5)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int, string) []*ent.Message); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageReader_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessageReader_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 *time.Time
//   - _a3 uuid.UUID
//   - _a4 int
//   - _a5 string
func (_e *MockMessageReader_Expecter) GetMessages(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}, _a5 interface{}) *MockMessageReader_GetMessages_Call {
	return &MockMessageReader_GetMessages_Call{Call: _e.mock.On("GetMessages", _a0, _a1, _a2, _a3, _a4, _a5)}
}

func (_c *MockMessageReader_GetMessages_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 *time.Time, _a3 uuid.UUID, _a4 int, _a5 string)) *MockMessageReader_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*time.Time), args[3].(uuid.UUID), args[4].(int), args[5].(string))
	})
	return _c
}

func (_c *MockMessageReader_GetMessages_Call) Return(_a0 []*ent.Message, _a1 error) *MockMessageReader_GetMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageReader_GetMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int, string) ([]*ent.Message, error)) *MockMessageReader_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessagesAround provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockMessageReader) GetMessagesAround(_a0 context.Context, _a1 uuid.UUID, _a2 *time.Time, _a3 uuid.UUID, _a4 int) ([]*ent.Message, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for GetMessagesAround")
	}

	var r0 []*ent.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int) ([]*ent.Message, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int) []*ent.Message); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageReader_GetMessagesAround_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessagesAround'
type MockMessageReader_GetMessagesAround_Call struct {
	*mock.Call
}

// GetMessagesAround is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 *time.Time
//   - _a3 uuid.UUID
//   - _a4 int
func (_e *MockMessageReader_Expecter) GetMessagesAround(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockMessageReader_GetMessagesAround_Call {
	return &MockMessageReader_GetMessagesAround_Call{Call: _e.mock.On("GetMessagesAround", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockMessageReader_GetMessagesAround_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 *time.Time, _a3 uuid.UUID, _a4 int)) *MockMessageReader_GetMessagesAround_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*time.Time), args[3].(uuid.UUID), args[4].(int))
	})
	return _c
}

func (_c *MockMessageReader_GetMessagesAround_Call) Return(_a0 []*ent.Message, _a1 error) *MockMessageReader_GetMessagesAround_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageReader_GetMessagesAround_Call) RunAndReturn(run func(context.Context, uuid.UUID, *time.Time, uuid.UUID, int) ([]*ent.Message, error)) *MockMessageReader_GetMessagesAround_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageReader creates a new instance of MockMessageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageReader {
	mock := &MockMessageReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
