// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockRateLimiter is an autogenerated mock type for the RateLimiter type
type MockRateLimiter struct {
	mock.Mock
}

type MockRateLimiter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRateLimiter) EXPECT() *MockRateLimiter_Expecter {
	return &MockRateLimiter_Expecter{mock: &_m.Mock}
}

// Allow provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockRateLimiter) Allow(_a0 context.Context, _a1 string, _a2 int, _a3 time.Duration) (bool, time.Duration, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Allow")
	}

	var r0 bool
	var r1 time.Duration
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) (bool, time.Duration, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, time.Duration) bool); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, time.Duration) time.Duration); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(time.Duration)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, time.Duration) error); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRateLimiter_Allow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Allow'
type MockRateLimiter_Allow_Call struct {
	*mock.Call
}

// Allow is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 int
//   - _a3 time.Duration
func (_e *MockRateLimiter_Expecter) Allow(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockRateLimiter_Allow_Call {
	return &MockRateLimiter_Allow_Call{Call: _e.mock.On("Allow", _a0, _a1, _a2, _a3)}
}

func (_c *MockRateLimiter_Allow_Call) Run(run func(_a0 context.Context, _a1 string, _a2 int, _a3 time.Duration)) *MockRateLimiter_Allow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRateLimiter_Allow_Call) Return(_a0 bool, _a1 time.Duration, _a2 error) *MockRateLimiter_Allow_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRateLimiter_Allow_Call) RunAndReturn(run func(context.Context, string, int, time.Duration) (bool, time.Duration, error)) *MockRateLimiter_Allow_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRateLimiter creates a new instance of MockRateLimiter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRateLimiter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRateLimiter {
	mock := &MockRateLimiter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
