// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	helper "AtoiTalkAPI/internal/helper"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// BlacklistToken provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSessionStore) BlacklistToken(_a0 context.Context, _a1 string, _a2 time.Duration) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_BlacklistToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistToken'
type MockSessionStore_BlacklistToken_Call struct {
	*mock.Call
}

// BlacklistToken is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 time.Duration
func (_e *MockSessionStore_Expecter) BlacklistToken(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSessionStore_BlacklistToken_Call {
	return &MockSessionStore_BlacklistToken_Call{Call: _e.mock.On("BlacklistToken", _a0, _a1, _a2)}
}

func (_c *MockSessionStore_BlacklistToken_Call) Run(run func(_a0 context.Context, _a1 string, _a2 time.Duration)) *MockSessionStore_BlacklistToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockSessionStore_BlacklistToken_Call) Return(_a0 error) *MockSessionStore_BlacklistToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_BlacklistToken_Call) RunAndReturn(run func(context.Context, string, time.Duration) error) *MockSessionStore_BlacklistToken_Call {
	_c.Call.Return(run)
	return _c
}

// IsUserRevoked provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSessionStore) IsUserRevoked(_a0 context.Context, _a1 uuid.UUID, _a2 int64) (bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for IsUserRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_IsUserRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUserRevoked'
type MockSessionStore_IsUserRevoked_Call struct {
	*mock.Call
}

// IsUserRevoked is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 int64
func (_e *MockSessionStore_Expecter) IsUserRevoked(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockSessionStore_IsUserRevoked_Call {
	return &MockSessionStore_IsUserRevoked_Call{Call: _e.mock.On("IsUserRevoked", _a0, _a1, _a2)}
}

func (_c *MockSessionStore_IsUserRevoked_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 int64)) *MockSessionStore_IsUserRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *MockSessionStore_IsUserRevoked_Call) Return(_a0 bool, _a1 error) *MockSessionStore_IsUserRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_IsUserRevoked_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (bool, error)) *MockSessionStore_IsUserRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessions provides a mock function with given fields: _a0, _a1
func (_m *MockSessionStore) RevokeAllSessions(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessions")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_RevokeAllSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessions'
type MockSessionStore_RevokeAllSessions_Call struct {
	*mock.Call
}

// RevokeAllSessions is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MockSessionStore_Expecter) RevokeAllSessions(_a0 interface{}, _a1 interface{}) *MockSessionStore_RevokeAllSessions_Call {
	return &MockSessionStore_RevokeAllSessions_Call{Call: _e.mock.On("RevokeAllSessions", _a0, _a1)}
}

func (_c *MockSessionStore_RevokeAllSessions_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MockSessionStore_RevokeAllSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionStore_RevokeAllSessions_Call) Return(_a0 error) *MockSessionStore_RevokeAllSessions_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_RevokeAllSessions_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockSessionStore_RevokeAllSessions_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllSessionsAt provides a mock function with given fields: ctx, userID, revokedAt
func (_m *MockSessionStore) RevokeAllSessionsAt(ctx context.Context, userID uuid.UUID, revokedAt int64) (string, error) {
	ret := _m.Called(ctx, userID, revokedAt)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllSessionsAt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) (string, error)); ok {
		return rf(ctx, userID, revokedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64) string); ok {
		r0 = rf(ctx, userID, revokedAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int64) error); ok {
		r1 = rf(ctx, userID, revokedAt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_RevokeAllSessionsAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllSessionsAt'
type MockSessionStore_RevokeAllSessionsAt_Call struct {
	*mock.Call
}

// RevokeAllSessionsAt is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - revokedAt int64
func (_e *MockSessionStore_Expecter) RevokeAllSessionsAt(ctx interface{}, userID interface{}, revokedAt interface{}) *MockSessionStore_RevokeAllSessionsAt_Call {
	return &MockSessionStore_RevokeAllSessionsAt_Call{Call: _e.mock.On("RevokeAllSessionsAt", ctx, userID, revokedAt)}
}

func (_c *MockSessionStore_RevokeAllSessionsAt_Call) Run(run func(ctx context.Context, userID uuid.UUID, revokedAt int64)) *MockSessionStore_RevokeAllSessionsAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int64))
	})
	return _c
}

func (_c *MockSessionStore_RevokeAllSessionsAt_Call) Return(_a0 string, _a1 error) *MockSessionStore_RevokeAllSessionsAt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_RevokeAllSessionsAt_Call) RunAndReturn(run func(context.Context, uuid.UUID, int64) (string, error)) *MockSessionStore_RevokeAllSessionsAt_Call {
	_c.Call.Return(run)
	return _c
}

// RollbackUserRevoke provides a mock function with given fields: ctx, userID, expectedValue, snapshot
func (_m *MockSessionStore) RollbackUserRevoke(ctx context.Context, userID uuid.UUID, expectedValue string, snapshot helper.SessionRevokeSnapshot) error {
	ret := _m.Called(ctx, userID, expectedValue, snapshot)

	if len(ret) == 0 {
		panic("no return value specified for RollbackUserRevoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, helper.SessionRevokeSnapshot) error); ok {
		r0 = rf(ctx, userID, expectedValue, snapshot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSessionStore_RollbackUserRevoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RollbackUserRevoke'
type MockSessionStore_RollbackUserRevoke_Call struct {
	*mock.Call
}

// RollbackUserRevoke is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - expectedValue string
//   - snapshot helper.SessionRevokeSnapshot
func (_e *MockSessionStore_Expecter) RollbackUserRevoke(ctx interface{}, userID interface{}, expectedValue interface{}, snapshot interface{}) *MockSessionStore_RollbackUserRevoke_Call {
	return &MockSessionStore_RollbackUserRevoke_Call{Call: _e.mock.On("RollbackUserRevoke", ctx, userID, expectedValue, snapshot)}
}

func (_c *MockSessionStore_RollbackUserRevoke_Call) Run(run func(ctx context.Context, userID uuid.UUID, expectedValue string, snapshot helper.SessionRevokeSnapshot)) *MockSessionStore_RollbackUserRevoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(helper.SessionRevokeSnapshot))
	})
	return _c
}

func (_c *MockSessionStore_RollbackUserRevoke_Call) Return(_a0 error) *MockSessionStore_RollbackUserRevoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSessionStore_RollbackUserRevoke_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, helper.SessionRevokeSnapshot) error) *MockSessionStore_RollbackUserRevoke_Call {
	_c.Call.Return(run)
	return _c
}

// SnapshotUserRevoke provides a mock function with given fields: ctx, userID
func (_m *MockSessionStore) SnapshotUserRevoke(ctx context.Context, userID uuid.UUID) (helper.SessionRevokeSnapshot, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SnapshotUserRevoke")
	}

	var r0 helper.SessionRevokeSnapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (helper.SessionRevokeSnapshot, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) helper.SessionRevokeSnapshot); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(helper.SessionRevokeSnapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSessionStore_SnapshotUserRevoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotUserRevoke'
type MockSessionStore_SnapshotUserRevoke_Call struct {
	*mock.Call
}

// SnapshotUserRevoke is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockSessionStore_Expecter) SnapshotUserRevoke(ctx interface{}, userID interface{}) *MockSessionStore_SnapshotUserRevoke_Call {
	return &MockSessionStore_SnapshotUserRevoke_Call{Call: _e.mock.On("SnapshotUserRevoke", ctx, userID)}
}

func (_c *MockSessionStore_SnapshotUserRevoke_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockSessionStore_SnapshotUserRevoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSessionStore_SnapshotUserRevoke_Call) Return(_a0 helper.SessionRevokeSnapshot, _a1 error) *MockSessionStore_SnapshotUserRevoke_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSessionStore_SnapshotUserRevoke_Call) RunAndReturn(run func(context.Context, uuid.UUID) (helper.SessionRevokeSnapshot, error)) *MockSessionStore_SnapshotUserRevoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
