// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenBlacklistStore is an autogenerated mock type for the TokenBlacklistStore type
type MockTokenBlacklistStore struct {
	mock.Mock
}

type MockTokenBlacklistStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenBlacklistStore) EXPECT() *MockTokenBlacklistStore_Expecter {
	return &MockTokenBlacklistStore_Expecter{mock: &_m.Mock}
}

// IsTokenBlacklisted provides a mock function with given fields: _a0, _a1
func (_m *MockTokenBlacklistStore) IsTokenBlacklisted(_a0 context.Context, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenBlacklistStore_IsTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenBlacklisted'
type MockTokenBlacklistStore_IsTokenBlacklisted_Call struct {
	*mock.Call
}

// IsTokenBlacklisted is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockTokenBlacklistStore_Expecter) IsTokenBlacklisted(_a0 interface{}, _a1 interface{}) *MockTokenBlacklistStore_IsTokenBlacklisted_Call {
	return &MockTokenBlacklistStore_IsTokenBlacklisted_Call{Call: _e.mock.On("IsTokenBlacklisted", _a0, _a1)}
}

func (_c *MockTokenBlacklistStore_IsTokenBlacklisted_Call) Run(run func(_a0 context.Context, _a1 string)) *MockTokenBlacklistStore_IsTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenBlacklistStore_IsTokenBlacklisted_Call) Return(_a0 bool, _a1 error) *MockTokenBlacklistStore_IsTokenBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenBlacklistStore_IsTokenBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenBlacklistStore_IsTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenBlacklistStore creates a new instance of MockTokenBlacklistStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenBlacklistStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenBlacklistStore {
	mock := &MockTokenBlacklistStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
