// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"

	websocket "AtoiTalkAPI/internal/websocket"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// BroadcastToChat provides a mock function with given fields: _a0, _a1
func (_m *MockPublisher) BroadcastToChat(_a0 uuid.UUID, _a1 websocket.Event) {
	_m.Called(_a0, _a1)
}

// MockPublisher_BroadcastToChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToChat'
type MockPublisher_BroadcastToChat_Call struct {
	*mock.Call
}

// BroadcastToChat is a helper method to define mock.On call
//   - _a0 uuid.UUID
//   - _a1 websocket.Event
func (_e *MockPublisher_Expecter) BroadcastToChat(_a0 interface{}, _a1 interface{}) *MockPublisher_BroadcastToChat_Call {
	return &MockPublisher_BroadcastToChat_Call{Call: _e.mock.On("BroadcastToChat", _a0, _a1)}
}

func (_c *MockPublisher_BroadcastToChat_Call) Run(run func(_a0 uuid.UUID, _a1 websocket.Event)) *MockPublisher_BroadcastToChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(websocket.Event))
	})
	return _c
}

func (_c *MockPublisher_BroadcastToChat_Call) Return() *MockPublisher_BroadcastToChat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_BroadcastToChat_Call) RunAndReturn(run func(uuid.UUID, websocket.Event)) *MockPublisher_BroadcastToChat_Call {
	_c.Run(run)
	return _c
}

// BroadcastToContacts provides a mock function with given fields: _a0, _a1
func (_m *MockPublisher) BroadcastToContacts(_a0 uuid.UUID, _a1 websocket.Event) {
	_m.Called(_a0, _a1)
}

// MockPublisher_BroadcastToContacts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToContacts'
type MockPublisher_BroadcastToContacts_Call struct {
	*mock.Call
}

// BroadcastToContacts is a helper method to define mock.On call
//   - _a0 uuid.UUID
//   - _a1 websocket.Event
func (_e *MockPublisher_Expecter) BroadcastToContacts(_a0 interface{}, _a1 interface{}) *MockPublisher_BroadcastToContacts_Call {
	return &MockPublisher_BroadcastToContacts_Call{Call: _e.mock.On("BroadcastToContacts", _a0, _a1)}
}

func (_c *MockPublisher_BroadcastToContacts_Call) Run(run func(_a0 uuid.UUID, _a1 websocket.Event)) *MockPublisher_BroadcastToContacts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(websocket.Event))
	})
	return _c
}

func (_c *MockPublisher_BroadcastToContacts_Call) Return() *MockPublisher_BroadcastToContacts_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_BroadcastToContacts_Call) RunAndReturn(run func(uuid.UUID, websocket.Event)) *MockPublisher_BroadcastToContacts_Call {
	_c.Run(run)
	return _c
}

// BroadcastToUser provides a mock function with given fields: _a0, _a1
func (_m *MockPublisher) BroadcastToUser(_a0 uuid.UUID, _a1 websocket.Event) {
	_m.Called(_a0, _a1)
}

// MockPublisher_BroadcastToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BroadcastToUser'
type MockPublisher_BroadcastToUser_Call struct {
	*mock.Call
}

// BroadcastToUser is a helper method to define mock.On call
//   - _a0 uuid.UUID
//   - _a1 websocket.Event
func (_e *MockPublisher_Expecter) BroadcastToUser(_a0 interface{}, _a1 interface{}) *MockPublisher_BroadcastToUser_Call {
	return &MockPublisher_BroadcastToUser_Call{Call: _e.mock.On("BroadcastToUser", _a0, _a1)}
}

func (_c *MockPublisher_BroadcastToUser_Call) Run(run func(_a0 uuid.UUID, _a1 websocket.Event)) *MockPublisher_BroadcastToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(websocket.Event))
	})
	return _c
}

func (_c *MockPublisher_BroadcastToUser_Call) Return() *MockPublisher_BroadcastToUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_BroadcastToUser_Call) RunAndReturn(run func(uuid.UUID, websocket.Event)) *MockPublisher_BroadcastToUser_Call {
	_c.Run(run)
	return _c
}

// DisconnectUser provides a mock function with given fields: _a0
func (_m *MockPublisher) DisconnectUser(_a0 uuid.UUID) {
	_m.Called(_a0)
}

// MockPublisher_DisconnectUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisconnectUser'
type MockPublisher_DisconnectUser_Call struct {
	*mock.Call
}

// DisconnectUser is a helper method to define mock.On call
//   - _a0 uuid.UUID
func (_e *MockPublisher_Expecter) DisconnectUser(_a0 interface{}) *MockPublisher_DisconnectUser_Call {
	return &MockPublisher_DisconnectUser_Call{Call: _e.mock.On("DisconnectUser", _a0)}
}

func (_c *MockPublisher_DisconnectUser_Call) Run(run func(_a0 uuid.UUID)) *MockPublisher_DisconnectUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockPublisher_DisconnectUser_Call) Return() *MockPublisher_DisconnectUser_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPublisher_DisconnectUser_Call) RunAndReturn(run func(uuid.UUID)) *MockPublisher_DisconnectUser_Call {
	_c.Run(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
