// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAccountServicePort is an autogenerated mock type for the AccountServicePort type
type MockAccountServicePort struct {
	mock.Mock
}

type MockAccountServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountServicePort) EXPECT() *MockAccountServicePort_Expecter {
	return &MockAccountServicePort_Expecter{mock: &_m.Mock}
}

// ChangeEmail provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAccountServicePort) ChangeEmail(_a0 context.Context, _a1 uuid.UUID, _a2 model.ChangeEmailRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ChangeEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.ChangeEmailRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountServicePort_ChangeEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeEmail'
type MockAccountServicePort_ChangeEmail_Call struct {
	*mock.Call
}

// ChangeEmail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.ChangeEmailRequest
func (_e *MockAccountServicePort_Expecter) ChangeEmail(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockAccountServicePort_ChangeEmail_Call {
	return &MockAccountServicePort_ChangeEmail_Call{Call: _e.mock.On("ChangeEmail", _a0, _a1, _a2)}
}

func (_c *MockAccountServicePort_ChangeEmail_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.ChangeEmailRequest)) *MockAccountServicePort_ChangeEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.ChangeEmailRequest))
	})
	return _c
}

func (_c *MockAccountServicePort_ChangeEmail_Call) Return(_a0 error) *MockAccountServicePort_ChangeEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountServicePort_ChangeEmail_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.ChangeEmailRequest) error) *MockAccountServicePort_ChangeEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ChangePassword provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAccountServicePort) ChangePassword(_a0 context.Context, _a1 uuid.UUID, _a2 model.ChangePasswordRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.ChangePasswordRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountServicePort_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type MockAccountServicePort_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.ChangePasswordRequest
func (_e *MockAccountServicePort_Expecter) ChangePassword(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockAccountServicePort_ChangePassword_Call {
	return &MockAccountServicePort_ChangePassword_Call{Call: _e.mock.On("ChangePassword", _a0, _a1, _a2)}
}

func (_c *MockAccountServicePort_ChangePassword_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.ChangePasswordRequest)) *MockAccountServicePort_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.ChangePasswordRequest))
	})
	return _c
}

func (_c *MockAccountServicePort_ChangePassword_Call) Return(_a0 error) *MockAccountServicePort_ChangePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountServicePort_ChangePassword_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.ChangePasswordRequest) error) *MockAccountServicePort_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAccount provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAccountServicePort) DeleteAccount(_a0 context.Context, _a1 uuid.UUID, _a2 model.DeleteAccountRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.DeleteAccountRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAccountServicePort_DeleteAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAccount'
type MockAccountServicePort_DeleteAccount_Call struct {
	*mock.Call
}

// DeleteAccount is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.DeleteAccountRequest
func (_e *MockAccountServicePort_Expecter) DeleteAccount(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockAccountServicePort_DeleteAccount_Call {
	return &MockAccountServicePort_DeleteAccount_Call{Call: _e.mock.On("DeleteAccount", _a0, _a1, _a2)}
}

func (_c *MockAccountServicePort_DeleteAccount_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.DeleteAccountRequest)) *MockAccountServicePort_DeleteAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.DeleteAccountRequest))
	})
	return _c
}

func (_c *MockAccountServicePort_DeleteAccount_Call) Return(_a0 error) *MockAccountServicePort_DeleteAccount_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAccountServicePort_DeleteAccount_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.DeleteAccountRequest) error) *MockAccountServicePort_DeleteAccount_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountServicePort creates a new instance of MockAccountServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountServicePort {
	mock := &MockAccountServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
