// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAdminServicePort is an autogenerated mock type for the AdminServicePort type
type MockAdminServicePort struct {
	mock.Mock
}

type MockAdminServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminServicePort) EXPECT() *MockAdminServicePort_Expecter {
	return &MockAdminServicePort_Expecter{mock: &_m.Mock}
}

// BanUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAdminServicePort) BanUser(_a0 context.Context, _a1 uuid.UUID, _a2 model.BanUserRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.BanUserRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServicePort_BanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BanUser'
type MockAdminServicePort_BanUser_Call struct {
	*mock.Call
}

// BanUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.BanUserRequest
func (_e *MockAdminServicePort_Expecter) BanUser(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockAdminServicePort_BanUser_Call {
	return &MockAdminServicePort_BanUser_Call{Call: _e.mock.On("BanUser", _a0, _a1, _a2)}
}

func (_c *MockAdminServicePort_BanUser_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.BanUserRequest)) *MockAdminServicePort_BanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.BanUserRequest))
	})
	return _c
}

func (_c *MockAdminServicePort_BanUser_Call) Return(_a0 error) *MockAdminServicePort_BanUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServicePort_BanUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.BanUserRequest) error) *MockAdminServicePort_BanUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReport provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) DeleteReport(_a0 context.Context, _a1 uuid.UUID) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServicePort_DeleteReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReport'
type MockAdminServicePort_DeleteReport_Call struct {
	*mock.Call
}

// DeleteReport is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MockAdminServicePort_Expecter) DeleteReport(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_DeleteReport_Call {
	return &MockAdminServicePort_DeleteReport_Call{Call: _e.mock.On("DeleteReport", _a0, _a1)}
}

func (_c *MockAdminServicePort_DeleteReport_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MockAdminServicePort_DeleteReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServicePort_DeleteReport_Call) Return(_a0 error) *MockAdminServicePort_DeleteReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServicePort_DeleteReport_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAdminServicePort_DeleteReport_Call {
	_c.Call.Return(run)
	return _c
}

// GetDashboardStats provides a mock function with given fields: _a0
func (_m *MockAdminServicePort) GetDashboardStats(_a0 context.Context) (*model.DashboardStatsResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardStats")
	}

	var r0 *model.DashboardStatsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.DashboardStatsResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.DashboardStatsResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.DashboardStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServicePort_GetDashboardStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboardStats'
type MockAdminServicePort_GetDashboardStats_Call struct {
	*mock.Call
}

// GetDashboardStats is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockAdminServicePort_Expecter) GetDashboardStats(_a0 interface{}) *MockAdminServicePort_GetDashboardStats_Call {
	return &MockAdminServicePort_GetDashboardStats_Call{Call: _e.mock.On("GetDashboardStats", _a0)}
}

func (_c *MockAdminServicePort_GetDashboardStats_Call) Run(run func(_a0 context.Context)) *MockAdminServicePort_GetDashboardStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAdminServicePort_GetDashboardStats_Call) Return(_a0 *model.DashboardStatsResponse, _a1 error) *MockAdminServicePort_GetDashboardStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServicePort_GetDashboardStats_Call) RunAndReturn(run func(context.Context) (*model.DashboardStatsResponse, error)) *MockAdminServicePort_GetDashboardStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupDetail provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) GetGroupDetail(_a0 context.Context, _a1 uuid.UUID) (*model.AdminGroupDetailResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupDetail")
	}

	var r0 *model.AdminGroupDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.AdminGroupDetailResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.AdminGroupDetailResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminGroupDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServicePort_GetGroupDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupDetail'
type MockAdminServicePort_GetGroupDetail_Call struct {
	*mock.Call
}

// GetGroupDetail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MockAdminServicePort_Expecter) GetGroupDetail(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_GetGroupDetail_Call {
	return &MockAdminServicePort_GetGroupDetail_Call{Call: _e.mock.On("GetGroupDetail", _a0, _a1)}
}

func (_c *MockAdminServicePort_GetGroupDetail_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MockAdminServicePort_GetGroupDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServicePort_GetGroupDetail_Call) Return(_a0 *model.AdminGroupDetailResponse, _a1 error) *MockAdminServicePort_GetGroupDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServicePort_GetGroupDetail_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.AdminGroupDetailResponse, error)) *MockAdminServicePort_GetGroupDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroups provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) GetGroups(_a0 context.Context, _a1 model.AdminGetGroupListRequest) ([]model.AdminGroupListResponse, string, bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetGroups")
	}

	var r0 []model.AdminGroupListResponse
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AdminGetGroupListRequest) ([]model.AdminGroupListResponse, string, bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AdminGetGroupListRequest) []model.AdminGroupListResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AdminGroupListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AdminGetGroupListRequest) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.AdminGetGroupListRequest) bool); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, model.AdminGetGroupListRequest) error); ok {
		r3 = rf(_a0, _a1)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAdminServicePort_GetGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroups'
type MockAdminServicePort_GetGroups_Call struct {
	*mock.Call
}

// GetGroups is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.AdminGetGroupListRequest
func (_e *MockAdminServicePort_Expecter) GetGroups(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_GetGroups_Call {
	return &MockAdminServicePort_GetGroups_Call{Call: _e.mock.On("GetGroups", _a0, _a1)}
}

func (_c *MockAdminServicePort_GetGroups_Call) Run(run func(_a0 context.Context, _a1 model.AdminGetGroupListRequest)) *MockAdminServicePort_GetGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AdminGetGroupListRequest))
	})
	return _c
}

func (_c *MockAdminServicePort_GetGroups_Call) Return(_a0 []model.AdminGroupListResponse, _a1 string, _a2 bool, _a3 error) *MockAdminServicePort_GetGroups_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAdminServicePort_GetGroups_Call) RunAndReturn(run func(context.Context, model.AdminGetGroupListRequest) ([]model.AdminGroupListResponse, string, bool, error)) *MockAdminServicePort_GetGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetReportDetail provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) GetReportDetail(_a0 context.Context, _a1 uuid.UUID) (*model.ReportDetailResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetReportDetail")
	}

	var r0 *model.ReportDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.ReportDetailResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.ReportDetailResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ReportDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServicePort_GetReportDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReportDetail'
type MockAdminServicePort_GetReportDetail_Call struct {
	*mock.Call
}

// GetReportDetail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MockAdminServicePort_Expecter) GetReportDetail(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_GetReportDetail_Call {
	return &MockAdminServicePort_GetReportDetail_Call{Call: _e.mock.On("GetReportDetail", _a0, _a1)}
}

func (_c *MockAdminServicePort_GetReportDetail_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MockAdminServicePort_GetReportDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServicePort_GetReportDetail_Call) Return(_a0 *model.ReportDetailResponse, _a1 error) *MockAdminServicePort_GetReportDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServicePort_GetReportDetail_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.ReportDetailResponse, error)) *MockAdminServicePort_GetReportDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetReports provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) GetReports(_a0 context.Context, _a1 model.GetReportsRequest) ([]model.ReportListResponse, string, bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetReports")
	}

	var r0 []model.ReportListResponse
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GetReportsRequest) ([]model.ReportListResponse, string, bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GetReportsRequest) []model.ReportListResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ReportListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GetReportsRequest) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.GetReportsRequest) bool); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, model.GetReportsRequest) error); ok {
		r3 = rf(_a0, _a1)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAdminServicePort_GetReports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReports'
type MockAdminServicePort_GetReports_Call struct {
	*mock.Call
}

// GetReports is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.GetReportsRequest
func (_e *MockAdminServicePort_Expecter) GetReports(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_GetReports_Call {
	return &MockAdminServicePort_GetReports_Call{Call: _e.mock.On("GetReports", _a0, _a1)}
}

func (_c *MockAdminServicePort_GetReports_Call) Run(run func(_a0 context.Context, _a1 model.GetReportsRequest)) *MockAdminServicePort_GetReports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GetReportsRequest))
	})
	return _c
}

func (_c *MockAdminServicePort_GetReports_Call) Return(_a0 []model.ReportListResponse, _a1 string, _a2 bool, _a3 error) *MockAdminServicePort_GetReports_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAdminServicePort_GetReports_Call) RunAndReturn(run func(context.Context, model.GetReportsRequest) ([]model.ReportListResponse, string, bool, error)) *MockAdminServicePort_GetReports_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserDetail provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) GetUserDetail(_a0 context.Context, _a1 uuid.UUID) (*model.AdminUserDetailResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUserDetail")
	}

	var r0 *model.AdminUserDetailResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.AdminUserDetailResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.AdminUserDetailResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AdminUserDetailResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAdminServicePort_GetUserDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserDetail'
type MockAdminServicePort_GetUserDetail_Call struct {
	*mock.Call
}

// GetUserDetail is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MockAdminServicePort_Expecter) GetUserDetail(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_GetUserDetail_Call {
	return &MockAdminServicePort_GetUserDetail_Call{Call: _e.mock.On("GetUserDetail", _a0, _a1)}
}

func (_c *MockAdminServicePort_GetUserDetail_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MockAdminServicePort_GetUserDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServicePort_GetUserDetail_Call) Return(_a0 *model.AdminUserDetailResponse, _a1 error) *MockAdminServicePort_GetUserDetail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAdminServicePort_GetUserDetail_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.AdminUserDetailResponse, error)) *MockAdminServicePort_GetUserDetail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsers provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) GetUsers(_a0 context.Context, _a1 model.AdminGetUserListRequest) ([]model.AdminUserListResponse, string, bool, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetUsers")
	}

	var r0 []model.AdminUserListResponse
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AdminGetUserListRequest) ([]model.AdminUserListResponse, string, bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AdminGetUserListRequest) []model.AdminUserListResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AdminUserListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AdminGetUserListRequest) string); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, model.AdminGetUserListRequest) bool); ok {
		r2 = rf(_a0, _a1)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, model.AdminGetUserListRequest) error); ok {
		r3 = rf(_a0, _a1)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockAdminServicePort_GetUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsers'
type MockAdminServicePort_GetUsers_Call struct {
	*mock.Call
}

// GetUsers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.AdminGetUserListRequest
func (_e *MockAdminServicePort_Expecter) GetUsers(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_GetUsers_Call {
	return &MockAdminServicePort_GetUsers_Call{Call: _e.mock.On("GetUsers", _a0, _a1)}
}

func (_c *MockAdminServicePort_GetUsers_Call) Run(run func(_a0 context.Context, _a1 model.AdminGetUserListRequest)) *MockAdminServicePort_GetUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AdminGetUserListRequest))
	})
	return _c
}

func (_c *MockAdminServicePort_GetUsers_Call) Return(_a0 []model.AdminUserListResponse, _a1 string, _a2 bool, _a3 error) *MockAdminServicePort_GetUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockAdminServicePort_GetUsers_Call) RunAndReturn(run func(context.Context, model.AdminGetUserListRequest) ([]model.AdminUserListResponse, string, bool, error)) *MockAdminServicePort_GetUsers_Call {
	_c.Call.Return(run)
	return _c
}

// ResetUserInfo provides a mock function with given fields: _a0, _a1
func (_m *MockAdminServicePort) ResetUserInfo(_a0 context.Context, _a1 model.ResetUserInfoRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ResetUserInfo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResetUserInfoRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServicePort_ResetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetUserInfo'
type MockAdminServicePort_ResetUserInfo_Call struct {
	*mock.Call
}

// ResetUserInfo is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.ResetUserInfoRequest
func (_e *MockAdminServicePort_Expecter) ResetUserInfo(_a0 interface{}, _a1 interface{}) *MockAdminServicePort_ResetUserInfo_Call {
	return &MockAdminServicePort_ResetUserInfo_Call{Call: _e.mock.On("ResetUserInfo", _a0, _a1)}
}

func (_c *MockAdminServicePort_ResetUserInfo_Call) Run(run func(_a0 context.Context, _a1 model.ResetUserInfoRequest)) *MockAdminServicePort_ResetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResetUserInfoRequest))
	})
	return _c
}

func (_c *MockAdminServicePort_ResetUserInfo_Call) Return(_a0 error) *MockAdminServicePort_ResetUserInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServicePort_ResetUserInfo_Call) RunAndReturn(run func(context.Context, model.ResetUserInfoRequest) error) *MockAdminServicePort_ResetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveReport provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockAdminServicePort) ResolveReport(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.ResolveReportRequest) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ResolveReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.ResolveReportRequest) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServicePort_ResolveReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveReport'
type MockAdminServicePort_ResolveReport_Call struct {
	*mock.Call
}

// ResolveReport is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 model.ResolveReportRequest
func (_e *MockAdminServicePort_Expecter) ResolveReport(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockAdminServicePort_ResolveReport_Call {
	return &MockAdminServicePort_ResolveReport_Call{Call: _e.mock.On("ResolveReport", _a0, _a1, _a2, _a3)}
}

func (_c *MockAdminServicePort_ResolveReport_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.ResolveReportRequest)) *MockAdminServicePort_ResolveReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.ResolveReportRequest))
	})
	return _c
}

func (_c *MockAdminServicePort_ResolveReport_Call) Return(_a0 error) *MockAdminServicePort_ResolveReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServicePort_ResolveReport_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.ResolveReportRequest) error) *MockAdminServicePort_ResolveReport_Call {
	_c.Call.Return(run)
	return _c
}

// UnbanUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAdminServicePort) UnbanUser(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UnbanUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAdminServicePort_UnbanUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnbanUser'
type MockAdminServicePort_UnbanUser_Call struct {
	*mock.Call
}

// UnbanUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockAdminServicePort_Expecter) UnbanUser(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockAdminServicePort_UnbanUser_Call {
	return &MockAdminServicePort_UnbanUser_Call{Call: _e.mock.On("UnbanUser", _a0, _a1, _a2)}
}

func (_c *MockAdminServicePort_UnbanUser_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockAdminServicePort_UnbanUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockAdminServicePort_UnbanUser_Call) Return(_a0 error) *MockAdminServicePort_UnbanUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAdminServicePort_UnbanUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockAdminServicePort_UnbanUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAdminServicePort creates a new instance of MockAdminServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminServicePort {
	mock := &MockAdminServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
