// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthVerifier is an autogenerated mock type for the AuthVerifier type
type MockAuthVerifier struct {
	mock.Mock
}

type MockAuthVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthVerifier) EXPECT() *MockAuthVerifier_Expecter {
	return &MockAuthVerifier_Expecter{mock: &_m.Mock}
}

// VerifyUser provides a mock function with given fields: _a0, _a1
func (_m *MockAuthVerifier) VerifyUser(_a0 context.Context, _a1 string) (*model.UserDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for VerifyUser")
	}

	var r0 *model.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthVerifier_VerifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyUser'
type MockAuthVerifier_VerifyUser_Call struct {
	*mock.Call
}

// VerifyUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockAuthVerifier_Expecter) VerifyUser(_a0 interface{}, _a1 interface{}) *MockAuthVerifier_VerifyUser_Call {
	return &MockAuthVerifier_VerifyUser_Call{Call: _e.mock.On("VerifyUser", _a0, _a1)}
}

func (_c *MockAuthVerifier_VerifyUser_Call) Run(run func(_a0 context.Context, _a1 string)) *MockAuthVerifier_VerifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthVerifier_VerifyUser_Call) Return(_a0 *model.UserDTO, _a1 error) *MockAuthVerifier_VerifyUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthVerifier_VerifyUser_Call) RunAndReturn(run func(context.Context, string) (*model.UserDTO, error)) *MockAuthVerifier_VerifyUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthVerifier creates a new instance of MockAuthVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthVerifier {
	mock := &MockAuthVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
