// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthServicePort is an autogenerated mock type for the AuthServicePort type
type MockAuthServicePort struct {
	mock.Mock
}

type MockAuthServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServicePort) EXPECT() *MockAuthServicePort_Expecter {
	return &MockAuthServicePort_Expecter{mock: &_m.Mock}
}

// BeginGoogleAuth provides a mock function with given fields: _a0
func (_m *MockAuthServicePort) BeginGoogleAuth(_a0 context.Context) (*model.GoogleAuthInitResponse, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for BeginGoogleAuth")
	}

	var r0 *model.GoogleAuthInitResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*model.GoogleAuthInitResponse, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *model.GoogleAuthInitResponse); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GoogleAuthInitResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicePort_BeginGoogleAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginGoogleAuth'
type MockAuthServicePort_BeginGoogleAuth_Call struct {
	*mock.Call
}

// BeginGoogleAuth is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockAuthServicePort_Expecter) BeginGoogleAuth(_a0 interface{}) *MockAuthServicePort_BeginGoogleAuth_Call {
	return &MockAuthServicePort_BeginGoogleAuth_Call{Call: _e.mock.On("BeginGoogleAuth", _a0)}
}

func (_c *MockAuthServicePort_BeginGoogleAuth_Call) Run(run func(_a0 context.Context)) *MockAuthServicePort_BeginGoogleAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockAuthServicePort_BeginGoogleAuth_Call) Return(_a0 *model.GoogleAuthInitResponse, _a1 error) *MockAuthServicePort_BeginGoogleAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicePort_BeginGoogleAuth_Call) RunAndReturn(run func(context.Context) (*model.GoogleAuthInitResponse, error)) *MockAuthServicePort_BeginGoogleAuth_Call {
	_c.Call.Return(run)
	return _c
}

// GoogleExchange provides a mock function with given fields: _a0, _a1
func (_m *MockAuthServicePort) GoogleExchange(_a0 context.Context, _a1 model.GoogleLoginRequest) (*model.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GoogleExchange")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GoogleLoginRequest) (*model.AuthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.GoogleLoginRequest) *model.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.GoogleLoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicePort_GoogleExchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GoogleExchange'
type MockAuthServicePort_GoogleExchange_Call struct {
	*mock.Call
}

// GoogleExchange is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.GoogleLoginRequest
func (_e *MockAuthServicePort_Expecter) GoogleExchange(_a0 interface{}, _a1 interface{}) *MockAuthServicePort_GoogleExchange_Call {
	return &MockAuthServicePort_GoogleExchange_Call{Call: _e.mock.On("GoogleExchange", _a0, _a1)}
}

func (_c *MockAuthServicePort_GoogleExchange_Call) Run(run func(_a0 context.Context, _a1 model.GoogleLoginRequest)) *MockAuthServicePort_GoogleExchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GoogleLoginRequest))
	})
	return _c
}

func (_c *MockAuthServicePort_GoogleExchange_Call) Return(_a0 *model.AuthResponse, _a1 error) *MockAuthServicePort_GoogleExchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicePort_GoogleExchange_Call) RunAndReturn(run func(context.Context, model.GoogleLoginRequest) (*model.AuthResponse, error)) *MockAuthServicePort_GoogleExchange_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *MockAuthServicePort) Login(_a0 context.Context, _a1 model.LoginRequest) (*model.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginRequest) (*model.AuthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.LoginRequest) *model.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.LoginRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicePort_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServicePort_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.LoginRequest
func (_e *MockAuthServicePort_Expecter) Login(_a0 interface{}, _a1 interface{}) *MockAuthServicePort_Login_Call {
	return &MockAuthServicePort_Login_Call{Call: _e.mock.On("Login", _a0, _a1)}
}

func (_c *MockAuthServicePort_Login_Call) Run(run func(_a0 context.Context, _a1 model.LoginRequest)) *MockAuthServicePort_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.LoginRequest))
	})
	return _c
}

func (_c *MockAuthServicePort_Login_Call) Return(_a0 *model.AuthResponse, _a1 error) *MockAuthServicePort_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicePort_Login_Call) RunAndReturn(run func(context.Context, model.LoginRequest) (*model.AuthResponse, error)) *MockAuthServicePort_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: _a0, _a1
func (_m *MockAuthServicePort) Logout(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicePort_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServicePort_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockAuthServicePort_Expecter) Logout(_a0 interface{}, _a1 interface{}) *MockAuthServicePort_Logout_Call {
	return &MockAuthServicePort_Logout_Call{Call: _e.mock.On("Logout", _a0, _a1)}
}

func (_c *MockAuthServicePort_Logout_Call) Run(run func(_a0 context.Context, _a1 string)) *MockAuthServicePort_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServicePort_Logout_Call) Return(_a0 error) *MockAuthServicePort_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicePort_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServicePort_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: _a0, _a1
func (_m *MockAuthServicePort) Register(_a0 context.Context, _a1 model.RegisterUserRequest) (*model.AuthResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.AuthResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RegisterUserRequest) (*model.AuthResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.RegisterUserRequest) *model.AuthResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.AuthResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.RegisterUserRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServicePort_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthServicePort_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.RegisterUserRequest
func (_e *MockAuthServicePort_Expecter) Register(_a0 interface{}, _a1 interface{}) *MockAuthServicePort_Register_Call {
	return &MockAuthServicePort_Register_Call{Call: _e.mock.On("Register", _a0, _a1)}
}

func (_c *MockAuthServicePort_Register_Call) Run(run func(_a0 context.Context, _a1 model.RegisterUserRequest)) *MockAuthServicePort_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.RegisterUserRequest))
	})
	return _c
}

func (_c *MockAuthServicePort_Register_Call) Return(_a0 *model.AuthResponse, _a1 error) *MockAuthServicePort_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServicePort_Register_Call) RunAndReturn(run func(context.Context, model.RegisterUserRequest) (*model.AuthResponse, error)) *MockAuthServicePort_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function with given fields: _a0, _a1
func (_m *MockAuthServicePort) ResetPassword(_a0 context.Context, _a1 model.ResetPasswordRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ResetPasswordRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServicePort_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type MockAuthServicePort_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.ResetPasswordRequest
func (_e *MockAuthServicePort_Expecter) ResetPassword(_a0 interface{}, _a1 interface{}) *MockAuthServicePort_ResetPassword_Call {
	return &MockAuthServicePort_ResetPassword_Call{Call: _e.mock.On("ResetPassword", _a0, _a1)}
}

func (_c *MockAuthServicePort_ResetPassword_Call) Run(run func(_a0 context.Context, _a1 model.ResetPasswordRequest)) *MockAuthServicePort_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ResetPasswordRequest))
	})
	return _c
}

func (_c *MockAuthServicePort_ResetPassword_Call) Return(_a0 error) *MockAuthServicePort_ResetPassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServicePort_ResetPassword_Call) RunAndReturn(run func(context.Context, model.ResetPasswordRequest) error) *MockAuthServicePort_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServicePort creates a new instance of MockAuthServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServicePort {
	mock := &MockAuthServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
