// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChatServicePort is an autogenerated mock type for the ChatServicePort type
type MockChatServicePort struct {
	mock.Mock
}

type MockChatServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatServicePort) EXPECT() *MockChatServicePort_Expecter {
	return &MockChatServicePort_Expecter{mock: &_m.Mock}
}

// GetChatByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockChatServicePort) GetChatByID(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.ChatListResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByID")
	}

	var r0 *model.ChatListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.ChatListResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.ChatListResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatServicePort_GetChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByID'
type MockChatServicePort_GetChatByID_Call struct {
	*mock.Call
}

// GetChatByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockChatServicePort_Expecter) GetChatByID(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockChatServicePort_GetChatByID_Call {
	return &MockChatServicePort_GetChatByID_Call{Call: _e.mock.On("GetChatByID", _a0, _a1, _a2)}
}

func (_c *MockChatServicePort_GetChatByID_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockChatServicePort_GetChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatServicePort_GetChatByID_Call) Return(_a0 *model.ChatListResponse, _a1 error) *MockChatServicePort_GetChatByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatServicePort_GetChatByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.ChatListResponse, error)) *MockChatServicePort_GetChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChats provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockChatServicePort) GetChats(_a0 context.Context, _a1 uuid.UUID, _a2 model.GetChatsRequest) ([]model.ChatListResponse, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetChats")
	}

	var r0 []model.ChatListResponse
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.GetChatsRequest) ([]model.ChatListResponse, string, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.GetChatsRequest) []model.ChatListResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChatListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.GetChatsRequest) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.GetChatsRequest) bool); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, model.GetChatsRequest) error); ok {
		r3 = rf(_a0, _a1, _a2)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockChatServicePort_GetChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChats'
type MockChatServicePort_GetChats_Call struct {
	*mock.Call
}

// GetChats is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.GetChatsRequest
func (_e *MockChatServicePort_Expecter) GetChats(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockChatServicePort_GetChats_Call {
	return &MockChatServicePort_GetChats_Call{Call: _e.mock.On("GetChats", _a0, _a1, _a2)}
}

func (_c *MockChatServicePort_GetChats_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.GetChatsRequest)) *MockChatServicePort_GetChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.GetChatsRequest))
	})
	return _c
}

func (_c *MockChatServicePort_GetChats_Call) Return(_a0 []model.ChatListResponse, _a1 string, _a2 bool, _a3 error) *MockChatServicePort_GetChats_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockChatServicePort_GetChats_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.GetChatsRequest) ([]model.ChatListResponse, string, bool, error)) *MockChatServicePort_GetChats_Call {
	_c.Call.Return(run)
	return _c
}

// HideChat provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockChatServicePort) HideChat(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for HideChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatServicePort_HideChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HideChat'
type MockChatServicePort_HideChat_Call struct {
	*mock.Call
}

// HideChat is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockChatServicePort_Expecter) HideChat(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockChatServicePort_HideChat_Call {
	return &MockChatServicePort_HideChat_Call{Call: _e.mock.On("HideChat", _a0, _a1, _a2)}
}

func (_c *MockChatServicePort_HideChat_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockChatServicePort_HideChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatServicePort_HideChat_Call) Return(_a0 error) *MockChatServicePort_HideChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatServicePort_HideChat_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockChatServicePort_HideChat_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsRead provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockChatServicePort) MarkAsRead(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatServicePort_MarkAsRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsRead'
type MockChatServicePort_MarkAsRead_Call struct {
	*mock.Call
}

// MarkAsRead is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockChatServicePort_Expecter) MarkAsRead(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockChatServicePort_MarkAsRead_Call {
	return &MockChatServicePort_MarkAsRead_Call{Call: _e.mock.On("MarkAsRead", _a0, _a1, _a2)}
}

func (_c *MockChatServicePort_MarkAsRead_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockChatServicePort_MarkAsRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatServicePort_MarkAsRead_Call) Return(_a0 error) *MockChatServicePort_MarkAsRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatServicePort_MarkAsRead_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockChatServicePort_MarkAsRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatServicePort creates a new instance of MockChatServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatServicePort {
	mock := &MockChatServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
