// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGroupChatServicePort is an autogenerated mock type for the GroupChatServicePort type
type MockGroupChatServicePort struct {
	mock.Mock
}

type MockGroupChatServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupChatServicePort) EXPECT() *MockGroupChatServicePort_Expecter {
	return &MockGroupChatServicePort_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockGroupChatServicePort) AddMember(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.AddGroupMemberRequest) ([]*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 []*model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.AddGroupMemberRequest) ([]*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.AddGroupMemberRequest) []*model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.AddGroupMemberRequest) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockGroupChatServicePort_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 model.AddGroupMemberRequest
func (_e *MockGroupChatServicePort_Expecter) AddMember(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockGroupChatServicePort_AddMember_Call {
	return &MockGroupChatServicePort_AddMember_Call{Call: _e.mock.On("AddMember", _a0, _a1, _a2, _a3)}
}

func (_c *MockGroupChatServicePort_AddMember_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.AddGroupMemberRequest)) *MockGroupChatServicePort_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.AddGroupMemberRequest))
	})
	return _c
}

func (_c *MockGroupChatServicePort_AddMember_Call) Return(_a0 []*model.MessageResponse, _a1 error) *MockGroupChatServicePort_AddMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.AddGroupMemberRequest) ([]*model.MessageResponse, error)) *MockGroupChatServicePort_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroupChat provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockGroupChatServicePort) CreateGroupChat(_a0 context.Context, _a1 uuid.UUID, _a2 model.CreateGroupChatRequest) (*model.ChatListResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroupChat")
	}

	var r0 *model.ChatListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateGroupChatRequest) (*model.ChatListResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateGroupChatRequest) *model.ChatListResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CreateGroupChatRequest) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_CreateGroupChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroupChat'
type MockGroupChatServicePort_CreateGroupChat_Call struct {
	*mock.Call
}

// CreateGroupChat is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.CreateGroupChatRequest
func (_e *MockGroupChatServicePort_Expecter) CreateGroupChat(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockGroupChatServicePort_CreateGroupChat_Call {
	return &MockGroupChatServicePort_CreateGroupChat_Call{Call: _e.mock.On("CreateGroupChat", _a0, _a1, _a2)}
}

func (_c *MockGroupChatServicePort_CreateGroupChat_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.CreateGroupChatRequest)) *MockGroupChatServicePort_CreateGroupChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreateGroupChatRequest))
	})
	return _c
}

func (_c *MockGroupChatServicePort_CreateGroupChat_Call) Return(_a0 *model.ChatListResponse, _a1 error) *MockGroupChatServicePort_CreateGroupChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_CreateGroupChat_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreateGroupChatRequest) (*model.ChatListResponse, error)) *MockGroupChatServicePort_CreateGroupChat_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGroup provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockGroupChatServicePort) DeleteGroup(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 bool) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupChatServicePort_DeleteGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroup'
type MockGroupChatServicePort_DeleteGroup_Call struct {
	*mock.Call
}

// DeleteGroup is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 bool
func (_e *MockGroupChatServicePort_Expecter) DeleteGroup(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockGroupChatServicePort_DeleteGroup_Call {
	return &MockGroupChatServicePort_DeleteGroup_Call{Call: _e.mock.On("DeleteGroup", _a0, _a1, _a2, _a3)}
}

func (_c *MockGroupChatServicePort_DeleteGroup_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 bool)) *MockGroupChatServicePort_DeleteGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(bool))
	})
	return _c
}

func (_c *MockGroupChatServicePort_DeleteGroup_Call) Return(_a0 error) *MockGroupChatServicePort_DeleteGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupChatServicePort_DeleteGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, bool) error) *MockGroupChatServicePort_DeleteGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupByInviteCode provides a mock function with given fields: _a0, _a1
func (_m *MockGroupChatServicePort) GetGroupByInviteCode(_a0 context.Context, _a1 string) (*model.GroupPreviewDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByInviteCode")
	}

	var r0 *model.GroupPreviewDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.GroupPreviewDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.GroupPreviewDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupPreviewDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_GetGroupByInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByInviteCode'
type MockGroupChatServicePort_GetGroupByInviteCode_Call struct {
	*mock.Call
}

// GetGroupByInviteCode is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockGroupChatServicePort_Expecter) GetGroupByInviteCode(_a0 interface{}, _a1 interface{}) *MockGroupChatServicePort_GetGroupByInviteCode_Call {
	return &MockGroupChatServicePort_GetGroupByInviteCode_Call{Call: _e.mock.On("GetGroupByInviteCode", _a0, _a1)}
}

func (_c *MockGroupChatServicePort_GetGroupByInviteCode_Call) Run(run func(_a0 context.Context, _a1 string)) *MockGroupChatServicePort_GetGroupByInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockGroupChatServicePort_GetGroupByInviteCode_Call) Return(_a0 *model.GroupPreviewDTO, _a1 error) *MockGroupChatServicePort_GetGroupByInviteCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_GetGroupByInviteCode_Call) RunAndReturn(run func(context.Context, string) (*model.GroupPreviewDTO, error)) *MockGroupChatServicePort_GetGroupByInviteCode_Call {
	_c.Call.Return(run)
	return _c
}

// JoinGroupByInvite provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockGroupChatServicePort) JoinGroupByInvite(_a0 context.Context, _a1 uuid.UUID, _a2 string) (*model.ChatListResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for JoinGroupByInvite")
	}

	var r0 *model.ChatListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*model.ChatListResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *model.ChatListResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_JoinGroupByInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinGroupByInvite'
type MockGroupChatServicePort_JoinGroupByInvite_Call struct {
	*mock.Call
}

// JoinGroupByInvite is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
func (_e *MockGroupChatServicePort_Expecter) JoinGroupByInvite(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockGroupChatServicePort_JoinGroupByInvite_Call {
	return &MockGroupChatServicePort_JoinGroupByInvite_Call{Call: _e.mock.On("JoinGroupByInvite", _a0, _a1, _a2)}
}

func (_c *MockGroupChatServicePort_JoinGroupByInvite_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string)) *MockGroupChatServicePort_JoinGroupByInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string))
	})
	return _c
}

func (_c *MockGroupChatServicePort_JoinGroupByInvite_Call) Return(_a0 *model.ChatListResponse, _a1 error) *MockGroupChatServicePort_JoinGroupByInvite_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_JoinGroupByInvite_Call) RunAndReturn(run func(context.Context, uuid.UUID, string) (*model.ChatListResponse, error)) *MockGroupChatServicePort_JoinGroupByInvite_Call {
	_c.Call.Return(run)
	return _c
}

// JoinPublicGroup provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockGroupChatServicePort) JoinPublicGroup(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.ChatListResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for JoinPublicGroup")
	}

	var r0 *model.ChatListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.ChatListResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.ChatListResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_JoinPublicGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinPublicGroup'
type MockGroupChatServicePort_JoinPublicGroup_Call struct {
	*mock.Call
}

// JoinPublicGroup is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockGroupChatServicePort_Expecter) JoinPublicGroup(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockGroupChatServicePort_JoinPublicGroup_Call {
	return &MockGroupChatServicePort_JoinPublicGroup_Call{Call: _e.mock.On("JoinPublicGroup", _a0, _a1, _a2)}
}

func (_c *MockGroupChatServicePort_JoinPublicGroup_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockGroupChatServicePort_JoinPublicGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupChatServicePort_JoinPublicGroup_Call) Return(_a0 *model.ChatListResponse, _a1 error) *MockGroupChatServicePort_JoinPublicGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_JoinPublicGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.ChatListResponse, error)) *MockGroupChatServicePort_JoinPublicGroup_Call {
	_c.Call.Return(run)
	return _c
}

// KickMember provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockGroupChatServicePort) KickMember(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 uuid.UUID) (*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for KickMember")
	}

	var r0 *model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) *model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_KickMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KickMember'
type MockGroupChatServicePort_KickMember_Call struct {
	*mock.Call
}

// KickMember is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 uuid.UUID
func (_e *MockGroupChatServicePort_Expecter) KickMember(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockGroupChatServicePort_KickMember_Call {
	return &MockGroupChatServicePort_KickMember_Call{Call: _e.mock.On("KickMember", _a0, _a1, _a2, _a3)}
}

func (_c *MockGroupChatServicePort_KickMember_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 uuid.UUID)) *MockGroupChatServicePort_KickMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupChatServicePort_KickMember_Call) Return(_a0 *model.MessageResponse, _a1 error) *MockGroupChatServicePort_KickMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_KickMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) (*model.MessageResponse, error)) *MockGroupChatServicePort_KickMember_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveGroup provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockGroupChatServicePort) LeaveGroup(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for LeaveGroup")
	}

	var r0 *model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_LeaveGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveGroup'
type MockGroupChatServicePort_LeaveGroup_Call struct {
	*mock.Call
}

// LeaveGroup is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockGroupChatServicePort_Expecter) LeaveGroup(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockGroupChatServicePort_LeaveGroup_Call {
	return &MockGroupChatServicePort_LeaveGroup_Call{Call: _e.mock.On("LeaveGroup", _a0, _a1, _a2)}
}

func (_c *MockGroupChatServicePort_LeaveGroup_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockGroupChatServicePort_LeaveGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupChatServicePort_LeaveGroup_Call) Return(_a0 *model.MessageResponse, _a1 error) *MockGroupChatServicePort_LeaveGroup_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_LeaveGroup_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.MessageResponse, error)) *MockGroupChatServicePort_LeaveGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ResetInviteCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockGroupChatServicePort) ResetInviteCode(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.GroupInviteResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ResetInviteCode")
	}

	var r0 *model.GroupInviteResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.GroupInviteResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.GroupInviteResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.GroupInviteResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_ResetInviteCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetInviteCode'
type MockGroupChatServicePort_ResetInviteCode_Call struct {
	*mock.Call
}

// ResetInviteCode is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockGroupChatServicePort_Expecter) ResetInviteCode(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockGroupChatServicePort_ResetInviteCode_Call {
	return &MockGroupChatServicePort_ResetInviteCode_Call{Call: _e.mock.On("ResetInviteCode", _a0, _a1, _a2)}
}

func (_c *MockGroupChatServicePort_ResetInviteCode_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockGroupChatServicePort_ResetInviteCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupChatServicePort_ResetInviteCode_Call) Return(_a0 *model.GroupInviteResponse, _a1 error) *MockGroupChatServicePort_ResetInviteCode_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_ResetInviteCode_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.GroupInviteResponse, error)) *MockGroupChatServicePort_ResetInviteCode_Call {
	_c.Call.Return(run)
	return _c
}

// SearchGroupMembers provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockGroupChatServicePort) SearchGroupMembers(_a0 context.Context, _a1 uuid.UUID, _a2 model.SearchGroupMembersRequest, _a3 bool) ([]model.GroupMemberDTO, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for SearchGroupMembers")
	}

	var r0 []model.GroupMemberDTO
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SearchGroupMembersRequest, bool) ([]model.GroupMemberDTO, string, bool, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SearchGroupMembersRequest, bool) []model.GroupMemberDTO); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.GroupMemberDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.SearchGroupMembersRequest, bool) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.SearchGroupMembersRequest, bool) bool); ok {
		r2 = rf(_a0, _a1, _a2, _a3)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, model.SearchGroupMembersRequest, bool) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockGroupChatServicePort_SearchGroupMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchGroupMembers'
type MockGroupChatServicePort_SearchGroupMembers_Call struct {
	*mock.Call
}

// SearchGroupMembers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.SearchGroupMembersRequest
//   - _a3 bool
func (_e *MockGroupChatServicePort_Expecter) SearchGroupMembers(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockGroupChatServicePort_SearchGroupMembers_Call {
	return &MockGroupChatServicePort_SearchGroupMembers_Call{Call: _e.mock.On("SearchGroupMembers", _a0, _a1, _a2, _a3)}
}

func (_c *MockGroupChatServicePort_SearchGroupMembers_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.SearchGroupMembersRequest, _a3 bool)) *MockGroupChatServicePort_SearchGroupMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.SearchGroupMembersRequest), args[3].(bool))
	})
	return _c
}

func (_c *MockGroupChatServicePort_SearchGroupMembers_Call) Return(_a0 []model.GroupMemberDTO, _a1 string, _a2 bool, _a3 error) *MockGroupChatServicePort_SearchGroupMembers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockGroupChatServicePort_SearchGroupMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.SearchGroupMembersRequest, bool) ([]model.GroupMemberDTO, string, bool, error)) *MockGroupChatServicePort_SearchGroupMembers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchPublicGroups provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockGroupChatServicePort) SearchPublicGroups(_a0 context.Context, _a1 uuid.UUID, _a2 model.SearchPublicGroupsRequest) ([]model.PublicGroupDTO, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SearchPublicGroups")
	}

	var r0 []model.PublicGroupDTO
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SearchPublicGroupsRequest) ([]model.PublicGroupDTO, string, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SearchPublicGroupsRequest) []model.PublicGroupDTO); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PublicGroupDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.SearchPublicGroupsRequest) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.SearchPublicGroupsRequest) bool); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, model.SearchPublicGroupsRequest) error); ok {
		r3 = rf(_a0, _a1, _a2)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockGroupChatServicePort_SearchPublicGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPublicGroups'
type MockGroupChatServicePort_SearchPublicGroups_Call struct {
	*mock.Call
}

// SearchPublicGroups is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.SearchPublicGroupsRequest
func (_e *MockGroupChatServicePort_Expecter) SearchPublicGroups(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockGroupChatServicePort_SearchPublicGroups_Call {
	return &MockGroupChatServicePort_SearchPublicGroups_Call{Call: _e.mock.On("SearchPublicGroups", _a0, _a1, _a2)}
}

func (_c *MockGroupChatServicePort_SearchPublicGroups_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.SearchPublicGroupsRequest)) *MockGroupChatServicePort_SearchPublicGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.SearchPublicGroupsRequest))
	})
	return _c
}

func (_c *MockGroupChatServicePort_SearchPublicGroups_Call) Return(_a0 []model.PublicGroupDTO, _a1 string, _a2 bool, _a3 error) *MockGroupChatServicePort_SearchPublicGroups_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockGroupChatServicePort_SearchPublicGroups_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.SearchPublicGroupsRequest) ([]model.PublicGroupDTO, string, bool, error)) *MockGroupChatServicePort_SearchPublicGroups_Call {
	_c.Call.Return(run)
	return _c
}

// TransferOwnership provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockGroupChatServicePort) TransferOwnership(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.TransferGroupOwnershipRequest) (*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransferOwnership")
	}

	var r0 *model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.TransferGroupOwnershipRequest) (*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.TransferGroupOwnershipRequest) *model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.TransferGroupOwnershipRequest) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_TransferOwnership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferOwnership'
type MockGroupChatServicePort_TransferOwnership_Call struct {
	*mock.Call
}

// TransferOwnership is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 model.TransferGroupOwnershipRequest
func (_e *MockGroupChatServicePort_Expecter) TransferOwnership(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockGroupChatServicePort_TransferOwnership_Call {
	return &MockGroupChatServicePort_TransferOwnership_Call{Call: _e.mock.On("TransferOwnership", _a0, _a1, _a2, _a3)}
}

func (_c *MockGroupChatServicePort_TransferOwnership_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.TransferGroupOwnershipRequest)) *MockGroupChatServicePort_TransferOwnership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.TransferGroupOwnershipRequest))
	})
	return _c
}

func (_c *MockGroupChatServicePort_TransferOwnership_Call) Return(_a0 *model.MessageResponse, _a1 error) *MockGroupChatServicePort_TransferOwnership_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_TransferOwnership_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.TransferGroupOwnershipRequest) (*model.MessageResponse, error)) *MockGroupChatServicePort_TransferOwnership_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGroupChat provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockGroupChatServicePort) UpdateGroupChat(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.UpdateGroupChatRequest, _a4 bool) (*model.ChatListResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGroupChat")
	}

	var r0 *model.ChatListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateGroupChatRequest, bool) (*model.ChatListResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateGroupChatRequest, bool) *model.ChatListResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.UpdateGroupChatRequest, bool) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_UpdateGroupChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGroupChat'
type MockGroupChatServicePort_UpdateGroupChat_Call struct {
	*mock.Call
}

// UpdateGroupChat is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 model.UpdateGroupChatRequest
//   - _a4 bool
func (_e *MockGroupChatServicePort_Expecter) UpdateGroupChat(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockGroupChatServicePort_UpdateGroupChat_Call {
	return &MockGroupChatServicePort_UpdateGroupChat_Call{Call: _e.mock.On("UpdateGroupChat", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockGroupChatServicePort_UpdateGroupChat_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.UpdateGroupChatRequest, _a4 bool)) *MockGroupChatServicePort_UpdateGroupChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.UpdateGroupChatRequest), args[4].(bool))
	})
	return _c
}

func (_c *MockGroupChatServicePort_UpdateGroupChat_Call) Return(_a0 *model.ChatListResponse, _a1 error) *MockGroupChatServicePort_UpdateGroupChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_UpdateGroupChat_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.UpdateGroupChatRequest, bool) (*model.ChatListResponse, error)) *MockGroupChatServicePort_UpdateGroupChat_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockGroupChatServicePort) UpdateMemberRole(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 uuid.UUID, _a4 model.UpdateGroupMemberRoleRequest) (*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 *model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, model.UpdateGroupMemberRoleRequest) (*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, model.UpdateGroupMemberRoleRequest) *model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, model.UpdateGroupMemberRoleRequest) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupChatServicePort_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MockGroupChatServicePort_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 uuid.UUID
//   - _a4 model.UpdateGroupMemberRoleRequest
func (_e *MockGroupChatServicePort_Expecter) UpdateMemberRole(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockGroupChatServicePort_UpdateMemberRole_Call {
	return &MockGroupChatServicePort_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockGroupChatServicePort_UpdateMemberRole_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 uuid.UUID, _a4 model.UpdateGroupMemberRoleRequest)) *MockGroupChatServicePort_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID), args[4].(model.UpdateGroupMemberRoleRequest))
	})
	return _c
}

func (_c *MockGroupChatServicePort_UpdateMemberRole_Call) Return(_a0 *model.MessageResponse, _a1 error) *MockGroupChatServicePort_UpdateMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupChatServicePort_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, model.UpdateGroupMemberRoleRequest) (*model.MessageResponse, error)) *MockGroupChatServicePort_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupChatServicePort creates a new instance of MockGroupChatServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupChatServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupChatServicePort {
	mock := &MockGroupChatServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
