// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMediaServicePort is an autogenerated mock type for the MediaServicePort type
type MockMediaServicePort struct {
	mock.Mock
}

type MockMediaServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMediaServicePort) EXPECT() *MockMediaServicePort_Expecter {
	return &MockMediaServicePort_Expecter{mock: &_m.Mock}
}

// CompleteUpload provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMediaServicePort) CompleteUpload(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.MediaDTO, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CompleteUpload")
	}

	var r0 *model.MediaDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.MediaDTO, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.MediaDTO); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MediaDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaServicePort_CompleteUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteUpload'
type MockMediaServicePort_CompleteUpload_Call struct {
	*mock.Call
}

// CompleteUpload is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockMediaServicePort_Expecter) CompleteUpload(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMediaServicePort_CompleteUpload_Call {
	return &MockMediaServicePort_CompleteUpload_Call{Call: _e.mock.On("CompleteUpload", _a0, _a1, _a2)}
}

func (_c *MockMediaServicePort_CompleteUpload_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockMediaServicePort_CompleteUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaServicePort_CompleteUpload_Call) Return(_a0 *model.MediaDTO, _a1 error) *MockMediaServicePort_CompleteUpload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaServicePort_CompleteUpload_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.MediaDTO, error)) *MockMediaServicePort_CompleteUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetMediaURL provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMediaServicePort) GetMediaURL(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.MediaURLResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetMediaURL")
	}

	var r0 *model.MediaURLResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.MediaURLResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.MediaURLResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MediaURLResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaServicePort_GetMediaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMediaURL'
type MockMediaServicePort_GetMediaURL_Call struct {
	*mock.Call
}

// GetMediaURL is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockMediaServicePort_Expecter) GetMediaURL(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMediaServicePort_GetMediaURL_Call {
	return &MockMediaServicePort_GetMediaURL_Call{Call: _e.mock.On("GetMediaURL", _a0, _a1, _a2)}
}

func (_c *MockMediaServicePort_GetMediaURL_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockMediaServicePort_GetMediaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockMediaServicePort_GetMediaURL_Call) Return(_a0 *model.MediaURLResponse, _a1 error) *MockMediaServicePort_GetMediaURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaServicePort_GetMediaURL_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.MediaURLResponse, error)) *MockMediaServicePort_GetMediaURL_Call {
	_c.Call.Return(run)
	return _c
}

// UploadMedia provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMediaServicePort) UploadMedia(_a0 context.Context, _a1 uuid.UUID, _a2 model.UploadMediaRequest) (*model.UploadMediaResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UploadMedia")
	}

	var r0 *model.UploadMediaResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UploadMediaRequest) (*model.UploadMediaResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UploadMediaRequest) *model.UploadMediaResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UploadMediaResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UploadMediaRequest) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMediaServicePort_UploadMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadMedia'
type MockMediaServicePort_UploadMedia_Call struct {
	*mock.Call
}

// UploadMedia is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.UploadMediaRequest
func (_e *MockMediaServicePort_Expecter) UploadMedia(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMediaServicePort_UploadMedia_Call {
	return &MockMediaServicePort_UploadMedia_Call{Call: _e.mock.On("UploadMedia", _a0, _a1, _a2)}
}

func (_c *MockMediaServicePort_UploadMedia_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.UploadMediaRequest)) *MockMediaServicePort_UploadMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UploadMediaRequest))
	})
	return _c
}

func (_c *MockMediaServicePort_UploadMedia_Call) Return(_a0 *model.UploadMediaResponse, _a1 error) *MockMediaServicePort_UploadMedia_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMediaServicePort_UploadMedia_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UploadMediaRequest) (*model.UploadMediaResponse, error)) *MockMediaServicePort_UploadMedia_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMediaServicePort creates a new instance of MockMediaServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMediaServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMediaServicePort {
	mock := &MockMediaServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
