// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockMessageServicePort is an autogenerated mock type for the MessageServicePort type
type MockMessageServicePort struct {
	mock.Mock
}

type MockMessageServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageServicePort) EXPECT() *MockMessageServicePort_Expecter {
	return &MockMessageServicePort_Expecter{mock: &_m.Mock}
}

// DeleteMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMessageServicePort) DeleteMessage(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageServicePort_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type MockMessageServicePort_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockMessageServicePort_Expecter) DeleteMessage(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMessageServicePort_DeleteMessage_Call {
	return &MockMessageServicePort_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", _a0, _a1, _a2)}
}

func (_c *MockMessageServicePort_DeleteMessage_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockMessageServicePort_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockMessageServicePort_DeleteMessage_Call) Return(_a0 error) *MockMessageServicePort_DeleteMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageServicePort_DeleteMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockMessageServicePort_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// EditMessage provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockMessageServicePort) EditMessage(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.EditMessageRequest) (*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for EditMessage")
	}

	var r0 *model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.EditMessageRequest) (*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, model.EditMessageRequest) *model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, model.EditMessageRequest) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageServicePort_EditMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EditMessage'
type MockMessageServicePort_EditMessage_Call struct {
	*mock.Call
}

// EditMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
//   - _a3 model.EditMessageRequest
func (_e *MockMessageServicePort_Expecter) EditMessage(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockMessageServicePort_EditMessage_Call {
	return &MockMessageServicePort_EditMessage_Call{Call: _e.mock.On("EditMessage", _a0, _a1, _a2, _a3)}
}

func (_c *MockMessageServicePort_EditMessage_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID, _a3 model.EditMessageRequest)) *MockMessageServicePort_EditMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(model.EditMessageRequest))
	})
	return _c
}

func (_c *MockMessageServicePort_EditMessage_Call) Return(_a0 *model.MessageResponse, _a1 error) *MockMessageServicePort_EditMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageServicePort_EditMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, model.EditMessageRequest) (*model.MessageResponse, error)) *MockMessageServicePort_EditMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessages provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMessageServicePort) GetMessages(_a0 context.Context, _a1 uuid.UUID, _a2 model.GetMessagesRequest) ([]model.MessageResponse, string, bool, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetMessages")
	}

	var r0 []model.MessageResponse
	var r1 string
	var r2 bool
	var r3 string
	var r4 bool
	var r5 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.GetMessagesRequest) ([]model.MessageResponse, string, bool, string, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.GetMessagesRequest) []model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.GetMessagesRequest) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.GetMessagesRequest) bool); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, model.GetMessagesRequest) string); ok {
		r3 = rf(_a0, _a1, _a2)
	} else {
		r3 = ret.Get(3).(string)
	}

	if rf, ok := ret.Get(4).(func(context.Context, uuid.UUID, model.GetMessagesRequest) bool); ok {
		r4 = rf(_a0, _a1, _a2)
	} else {
		r4 = ret.Get(4).(bool)
	}

	if rf, ok := ret.Get(5).(func(context.Context, uuid.UUID, model.GetMessagesRequest) error); ok {
		r5 = rf(_a0, _a1, _a2)
	} else {
		r5 = ret.Error(5)
	}

	return r0, r1, r2, r3, r4, r5
}

// MockMessageServicePort_GetMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessages'
type MockMessageServicePort_GetMessages_Call struct {
	*mock.Call
}

// GetMessages is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.GetMessagesRequest
func (_e *MockMessageServicePort_Expecter) GetMessages(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMessageServicePort_GetMessages_Call {
	return &MockMessageServicePort_GetMessages_Call{Call: _e.mock.On("GetMessages", _a0, _a1, _a2)}
}

func (_c *MockMessageServicePort_GetMessages_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.GetMessagesRequest)) *MockMessageServicePort_GetMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.GetMessagesRequest))
	})
	return _c
}

func (_c *MockMessageServicePort_GetMessages_Call) Return(_a0 []model.MessageResponse, _a1 string, _a2 bool, _a3 string, _a4 bool, _a5 error) *MockMessageServicePort_GetMessages_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3, _a4, _a5)
	return _c
}

func (_c *MockMessageServicePort_GetMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.GetMessagesRequest) ([]model.MessageResponse, string, bool, string, bool, error)) *MockMessageServicePort_GetMessages_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockMessageServicePort) SendMessage(_a0 context.Context, _a1 uuid.UUID, _a2 model.SendMessageRequest) (*model.MessageResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *model.MessageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SendMessageRequest) (*model.MessageResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SendMessageRequest) *model.MessageResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.MessageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.SendMessageRequest) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageServicePort_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockMessageServicePort_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.SendMessageRequest
func (_e *MockMessageServicePort_Expecter) SendMessage(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockMessageServicePort_SendMessage_Call {
	return &MockMessageServicePort_SendMessage_Call{Call: _e.mock.On("SendMessage", _a0, _a1, _a2)}
}

func (_c *MockMessageServicePort_SendMessage_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.SendMessageRequest)) *MockMessageServicePort_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.SendMessageRequest))
	})
	return _c
}

func (_c *MockMessageServicePort_SendMessage_Call) Return(_a0 *model.MessageResponse, _a1 error) *MockMessageServicePort_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageServicePort_SendMessage_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.SendMessageRequest) (*model.MessageResponse, error)) *MockMessageServicePort_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageServicePort creates a new instance of MockMessageServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageServicePort {
	mock := &MockMessageServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
