// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOTPServicePort is an autogenerated mock type for the OTPServicePort type
type MockOTPServicePort struct {
	mock.Mock
}

type MockOTPServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOTPServicePort) EXPECT() *MockOTPServicePort_Expecter {
	return &MockOTPServicePort_Expecter{mock: &_m.Mock}
}

// SendOTP provides a mock function with given fields: _a0, _a1
func (_m *MockOTPServicePort) SendOTP(_a0 context.Context, _a1 model.SendOTPRequest) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SendOTP")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.SendOTPRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOTPServicePort_SendOTP_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendOTP'
type MockOTPServicePort_SendOTP_Call struct {
	*mock.Call
}

// SendOTP is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 model.SendOTPRequest
func (_e *MockOTPServicePort_Expecter) SendOTP(_a0 interface{}, _a1 interface{}) *MockOTPServicePort_SendOTP_Call {
	return &MockOTPServicePort_SendOTP_Call{Call: _e.mock.On("SendOTP", _a0, _a1)}
}

func (_c *MockOTPServicePort_SendOTP_Call) Run(run func(_a0 context.Context, _a1 model.SendOTPRequest)) *MockOTPServicePort_SendOTP_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.SendOTPRequest))
	})
	return _c
}

func (_c *MockOTPServicePort_SendOTP_Call) Return(_a0 error) *MockOTPServicePort_SendOTP_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOTPServicePort_SendOTP_Call) RunAndReturn(run func(context.Context, model.SendOTPRequest) error) *MockOTPServicePort_SendOTP_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOTPServicePort creates a new instance of MockOTPServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOTPServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOTPServicePort {
	mock := &MockOTPServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
