// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockPrivateChatServicePort is an autogenerated mock type for the PrivateChatServicePort type
type MockPrivateChatServicePort struct {
	mock.Mock
}

type MockPrivateChatServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPrivateChatServicePort) EXPECT() *MockPrivateChatServicePort_Expecter {
	return &MockPrivateChatServicePort_Expecter{mock: &_m.Mock}
}

// CreatePrivateChat provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockPrivateChatServicePort) CreatePrivateChat(_a0 context.Context, _a1 uuid.UUID, _a2 model.CreatePrivateChatRequest) (*model.ChatResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreatePrivateChat")
	}

	var r0 *model.ChatResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreatePrivateChatRequest) (*model.ChatResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreatePrivateChatRequest) *model.ChatResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.CreatePrivateChatRequest) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPrivateChatServicePort_CreatePrivateChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatePrivateChat'
type MockPrivateChatServicePort_CreatePrivateChat_Call struct {
	*mock.Call
}

// CreatePrivateChat is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.CreatePrivateChatRequest
func (_e *MockPrivateChatServicePort_Expecter) CreatePrivateChat(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockPrivateChatServicePort_CreatePrivateChat_Call {
	return &MockPrivateChatServicePort_CreatePrivateChat_Call{Call: _e.mock.On("CreatePrivateChat", _a0, _a1, _a2)}
}

func (_c *MockPrivateChatServicePort_CreatePrivateChat_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.CreatePrivateChatRequest)) *MockPrivateChatServicePort_CreatePrivateChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreatePrivateChatRequest))
	})
	return _c
}

func (_c *MockPrivateChatServicePort_CreatePrivateChat_Call) Return(_a0 *model.ChatResponse, _a1 error) *MockPrivateChatServicePort_CreatePrivateChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPrivateChatServicePort_CreatePrivateChat_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreatePrivateChatRequest) (*model.ChatResponse, error)) *MockPrivateChatServicePort_CreatePrivateChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPrivateChatServicePort creates a new instance of MockPrivateChatServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPrivateChatServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPrivateChatServicePort {
	mock := &MockPrivateChatServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
