// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockReportServicePort is an autogenerated mock type for the ReportServicePort type
type MockReportServicePort struct {
	mock.Mock
}

type MockReportServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportServicePort) EXPECT() *MockReportServicePort_Expecter {
	return &MockReportServicePort_Expecter{mock: &_m.Mock}
}

// CreateReport provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockReportServicePort) CreateReport(_a0 context.Context, _a1 uuid.UUID, _a2 model.CreateReportRequest) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateReport")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.CreateReportRequest) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportServicePort_CreateReport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReport'
type MockReportServicePort_CreateReport_Call struct {
	*mock.Call
}

// CreateReport is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.CreateReportRequest
func (_e *MockReportServicePort_Expecter) CreateReport(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockReportServicePort_CreateReport_Call {
	return &MockReportServicePort_CreateReport_Call{Call: _e.mock.On("CreateReport", _a0, _a1, _a2)}
}

func (_c *MockReportServicePort_CreateReport_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.CreateReportRequest)) *MockReportServicePort_CreateReport_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.CreateReportRequest))
	})
	return _c
}

func (_c *MockReportServicePort_CreateReport_Call) Return(_a0 error) *MockReportServicePort_CreateReport_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportServicePort_CreateReport_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.CreateReportRequest) error) *MockReportServicePort_CreateReport_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportServicePort creates a new instance of MockReportServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportServicePort {
	mock := &MockReportServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
