// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	model "AtoiTalkAPI/internal/model"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserServicePort is an autogenerated mock type for the UserServicePort type
type MockUserServicePort struct {
	mock.Mock
}

type MockUserServicePort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserServicePort) EXPECT() *MockUserServicePort_Expecter {
	return &MockUserServicePort_Expecter{mock: &_m.Mock}
}

// BlockUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServicePort) BlockUser(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BlockUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServicePort_BlockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockUser'
type MockUserServicePort_BlockUser_Call struct {
	*mock.Call
}

// BlockUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockUserServicePort_Expecter) BlockUser(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServicePort_BlockUser_Call {
	return &MockUserServicePort_BlockUser_Call{Call: _e.mock.On("BlockUser", _a0, _a1, _a2)}
}

func (_c *MockUserServicePort_BlockUser_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockUserServicePort_BlockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServicePort_BlockUser_Call) Return(_a0 error) *MockUserServicePort_BlockUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServicePort_BlockUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockUserServicePort_BlockUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockedUsers provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServicePort) GetBlockedUsers(_a0 context.Context, _a1 uuid.UUID, _a2 model.GetBlockedUsersRequest) ([]model.UserDTO, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedUsers")
	}

	var r0 []model.UserDTO
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.GetBlockedUsersRequest) ([]model.UserDTO, string, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.GetBlockedUsersRequest) []model.UserDTO); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.GetBlockedUsersRequest) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.GetBlockedUsersRequest) bool); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, model.GetBlockedUsersRequest) error); ok {
		r3 = rf(_a0, _a1, _a2)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserServicePort_GetBlockedUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedUsers'
type MockUserServicePort_GetBlockedUsers_Call struct {
	*mock.Call
}

// GetBlockedUsers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.GetBlockedUsersRequest
func (_e *MockUserServicePort_Expecter) GetBlockedUsers(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServicePort_GetBlockedUsers_Call {
	return &MockUserServicePort_GetBlockedUsers_Call{Call: _e.mock.On("GetBlockedUsers", _a0, _a1, _a2)}
}

func (_c *MockUserServicePort_GetBlockedUsers_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.GetBlockedUsersRequest)) *MockUserServicePort_GetBlockedUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.GetBlockedUsersRequest))
	})
	return _c
}

func (_c *MockUserServicePort_GetBlockedUsers_Call) Return(_a0 []model.UserDTO, _a1 string, _a2 bool, _a3 error) *MockUserServicePort_GetBlockedUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockUserServicePort_GetBlockedUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.GetBlockedUsersRequest) ([]model.UserDTO, string, bool, error)) *MockUserServicePort_GetBlockedUsers_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrentUser provides a mock function with given fields: _a0, _a1
func (_m *MockUserServicePort) GetCurrentUser(_a0 context.Context, _a1 uuid.UUID) (*model.UserDTO, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentUser")
	}

	var r0 *model.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.UserDTO, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.UserDTO); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServicePort_GetCurrentUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentUser'
type MockUserServicePort_GetCurrentUser_Call struct {
	*mock.Call
}

// GetCurrentUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
func (_e *MockUserServicePort_Expecter) GetCurrentUser(_a0 interface{}, _a1 interface{}) *MockUserServicePort_GetCurrentUser_Call {
	return &MockUserServicePort_GetCurrentUser_Call{Call: _e.mock.On("GetCurrentUser", _a0, _a1)}
}

func (_c *MockUserServicePort_GetCurrentUser_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID)) *MockUserServicePort_GetCurrentUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServicePort_GetCurrentUser_Call) Return(_a0 *model.UserDTO, _a1 error) *MockUserServicePort_GetCurrentUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServicePort_GetCurrentUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.UserDTO, error)) *MockUserServicePort_GetCurrentUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProfile provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServicePort) GetUserProfile(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*model.UserDTO, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *model.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*model.UserDTO, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *model.UserDTO); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServicePort_GetUserProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProfile'
type MockUserServicePort_GetUserProfile_Call struct {
	*mock.Call
}

// GetUserProfile is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockUserServicePort_Expecter) GetUserProfile(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServicePort_GetUserProfile_Call {
	return &MockUserServicePort_GetUserProfile_Call{Call: _e.mock.On("GetUserProfile", _a0, _a1, _a2)}
}

func (_c *MockUserServicePort_GetUserProfile_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockUserServicePort_GetUserProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServicePort_GetUserProfile_Call) Return(_a0 *model.UserDTO, _a1 error) *MockUserServicePort_GetUserProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServicePort_GetUserProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*model.UserDTO, error)) *MockUserServicePort_GetUserProfile_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServicePort) SearchUsers(_a0 context.Context, _a1 uuid.UUID, _a2 model.SearchUserRequest) ([]model.UserDTO, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []model.UserDTO
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SearchUserRequest) ([]model.UserDTO, string, bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.SearchUserRequest) []model.UserDTO); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.SearchUserRequest) string); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, model.SearchUserRequest) bool); ok {
		r2 = rf(_a0, _a1, _a2)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, model.SearchUserRequest) error); ok {
		r3 = rf(_a0, _a1, _a2)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserServicePort_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUserServicePort_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.SearchUserRequest
func (_e *MockUserServicePort_Expecter) SearchUsers(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServicePort_SearchUsers_Call {
	return &MockUserServicePort_SearchUsers_Call{Call: _e.mock.On("SearchUsers", _a0, _a1, _a2)}
}

func (_c *MockUserServicePort_SearchUsers_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.SearchUserRequest)) *MockUserServicePort_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.SearchUserRequest))
	})
	return _c
}

func (_c *MockUserServicePort_SearchUsers_Call) Return(_a0 []model.UserDTO, _a1 string, _a2 bool, _a3 error) *MockUserServicePort_SearchUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockUserServicePort_SearchUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.SearchUserRequest) ([]model.UserDTO, string, bool, error)) *MockUserServicePort_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockUser provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServicePort) UnblockUser(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UnblockUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserServicePort_UnblockUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockUser'
type MockUserServicePort_UnblockUser_Call struct {
	*mock.Call
}

// UnblockUser is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockUserServicePort_Expecter) UnblockUser(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServicePort_UnblockUser_Call {
	return &MockUserServicePort_UnblockUser_Call{Call: _e.mock.On("UnblockUser", _a0, _a1, _a2)}
}

func (_c *MockUserServicePort_UnblockUser_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockUserServicePort_UnblockUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserServicePort_UnblockUser_Call) Return(_a0 error) *MockUserServicePort_UnblockUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserServicePort_UnblockUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockUserServicePort_UnblockUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockUserServicePort) UpdateProfile(_a0 context.Context, _a1 uuid.UUID, _a2 model.UpdateProfileRequest) (*model.UserDTO, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *model.UserDTO
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateProfileRequest) (*model.UserDTO, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, model.UpdateProfileRequest) *model.UserDTO); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserDTO)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, model.UpdateProfileRequest) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserServicePort_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockUserServicePort_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 model.UpdateProfileRequest
func (_e *MockUserServicePort_Expecter) UpdateProfile(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockUserServicePort_UpdateProfile_Call {
	return &MockUserServicePort_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", _a0, _a1, _a2)}
}

func (_c *MockUserServicePort_UpdateProfile_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 model.UpdateProfileRequest)) *MockUserServicePort_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(model.UpdateProfileRequest))
	})
	return _c
}

func (_c *MockUserServicePort_UpdateProfile_Call) Return(_a0 *model.UserDTO, _a1 error) *MockUserServicePort_UpdateProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserServicePort_UpdateProfile_Call) RunAndReturn(run func(context.Context, uuid.UUID, model.UpdateProfileRequest) (*model.UserDTO, error)) *MockUserServicePort_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserServicePort creates a new instance of MockUserServicePort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserServicePort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserServicePort {
	mock := &MockUserServicePort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
