// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ent "AtoiTalkAPI/ent"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChatReader is an autogenerated mock type for the ChatReader type
type MockChatReader struct {
	mock.Mock
}

type MockChatReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatReader) EXPECT() *MockChatReader_Expecter {
	return &MockChatReader_Expecter{mock: &_m.Mock}
}

// GetChatByID provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockChatReader) GetChatByID(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID) (*ent.Chat, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetChatByID")
	}

	var r0 *ent.Chat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*ent.Chat, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *ent.Chat); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ent.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatReader_GetChatByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatByID'
type MockChatReader_GetChatByID_Call struct {
	*mock.Call
}

// GetChatByID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 uuid.UUID
func (_e *MockChatReader_Expecter) GetChatByID(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockChatReader_GetChatByID_Call {
	return &MockChatReader_GetChatByID_Call{Call: _e.mock.On("GetChatByID", _a0, _a1, _a2)}
}

func (_c *MockChatReader_GetChatByID_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 uuid.UUID)) *MockChatReader_GetChatByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatReader_GetChatByID_Call) Return(_a0 *ent.Chat, _a1 error) *MockChatReader_GetChatByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatReader_GetChatByID_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*ent.Chat, error)) *MockChatReader_GetChatByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetChats provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockChatReader) GetChats(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int) ([]*ent.Chat, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for GetChats")
	}

	var r0 []*ent.Chat
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) ([]*ent.Chat, string, bool, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) []*ent.Chat); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.Chat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, string, int) bool); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, string, string, int) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockChatReader_GetChats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChats'
type MockChatReader_GetChats_Call struct {
	*mock.Call
}

// GetChats is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
//   - _a3 string
//   - _a4 int
func (_e *MockChatReader_Expecter) GetChats(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockChatReader_GetChats_Call {
	return &MockChatReader_GetChats_Call{Call: _e.mock.On("GetChats", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockChatReader_GetChats_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int)) *MockChatReader_GetChats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockChatReader_GetChats_Call) Return(_a0 []*ent.Chat, _a1 string, _a2 bool, _a3 error) *MockChatReader_GetChats_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockChatReader_GetChats_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, int) ([]*ent.Chat, string, bool, error)) *MockChatReader_GetChats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatReader creates a new instance of MockChatReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatReader {
	mock := &MockChatReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
