// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ent "AtoiTalkAPI/ent"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGroupChatReader is an autogenerated mock type for the GroupChatReader type
type MockGroupChatReader struct {
	mock.Mock
}

type MockGroupChatReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupChatReader) EXPECT() *MockGroupChatReader_Expecter {
	return &MockGroupChatReader_Expecter{mock: &_m.Mock}
}

// SearchPublicGroups provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockGroupChatReader) SearchPublicGroups(_a0 context.Context, _a1 string, _a2 string, _a3 int, _a4 string) ([]*ent.GroupChat, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for SearchPublicGroups")
	}

	var r0 []*ent.GroupChat
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string) ([]*ent.GroupChat, string, bool, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string) []*ent.GroupChat); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.GroupChat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, string) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, string) bool); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, string, string, int, string) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockGroupChatReader_SearchPublicGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchPublicGroups'
type MockGroupChatReader_SearchPublicGroups_Call struct {
	*mock.Call
}

// SearchPublicGroups is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 string
//   - _a3 int
//   - _a4 string
func (_e *MockGroupChatReader_Expecter) SearchPublicGroups(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockGroupChatReader_SearchPublicGroups_Call {
	return &MockGroupChatReader_SearchPublicGroups_Call{Call: _e.mock.On("SearchPublicGroups", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockGroupChatReader_SearchPublicGroups_Call) Run(run func(_a0 context.Context, _a1 string, _a2 string, _a3 int, _a4 string)) *MockGroupChatReader_SearchPublicGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(string))
	})
	return _c
}

func (_c *MockGroupChatReader_SearchPublicGroups_Call) Return(_a0 []*ent.GroupChat, _a1 string, _a2 bool, _a3 error) *MockGroupChatReader_SearchPublicGroups_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockGroupChatReader_SearchPublicGroups_Call) RunAndReturn(run func(context.Context, string, string, int, string) ([]*ent.GroupChat, string, bool, error)) *MockGroupChatReader_SearchPublicGroups_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupChatReader creates a new instance of MockGroupChatReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupChatReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupChatReader {
	mock := &MockGroupChatReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
