// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	ent "AtoiTalkAPI/ent"
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserReader is an autogenerated mock type for the UserReader type
type MockUserReader struct {
	mock.Mock
}

type MockUserReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserReader) EXPECT() *MockUserReader_Expecter {
	return &MockUserReader_Expecter{mock: &_m.Mock}
}

// GetBlockedUsers provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockUserReader) GetBlockedUsers(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int) ([]*ent.User, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockedUsers")
	}

	var r0 []*ent.User
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) ([]*ent.User, string, bool, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int) []*ent.User); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, string, int) bool); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, string, string, int) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserReader_GetBlockedUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockedUsers'
type MockUserReader_GetBlockedUsers_Call struct {
	*mock.Call
}

// GetBlockedUsers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
//   - _a3 string
//   - _a4 int
func (_e *MockUserReader_Expecter) GetBlockedUsers(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockUserReader_GetBlockedUsers_Call {
	return &MockUserReader_GetBlockedUsers_Call{Call: _e.mock.On("GetBlockedUsers", _a0, _a1, _a2, _a3, _a4)}
}

func (_c *MockUserReader_GetBlockedUsers_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int)) *MockUserReader_GetBlockedUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockUserReader_GetBlockedUsers_Call) Return(_a0 []*ent.User, _a1 string, _a2 bool, _a3 error) *MockUserReader_GetBlockedUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockUserReader_GetBlockedUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, int) ([]*ent.User, string, bool, error)) *MockUserReader_GetBlockedUsers_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4, _a5
func (_m *MockUserReader) SearchUsers(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int, _a5 *uuid.UUID) ([]*ent.User, string, bool, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4, _a5)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*ent.User
	var r1 string
	var r2 bool
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int, *uuid.UUID) ([]*ent.User, string, bool, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4, _a5)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, int, *uuid.UUID) []*ent.User); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ent.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, int, *uuid.UUID) string); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, string, string, int, *uuid.UUID) bool); ok {
		r2 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r2 = ret.Get(2).(bool)
	}

	if rf, ok := ret.Get(3).(func(context.Context, uuid.UUID, string, string, int, *uuid.UUID) error); ok {
		r3 = rf(_a0, _a1, _a2, _a3, _a4, _a5)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// MockUserReader_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type MockUserReader_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 uuid.UUID
//   - _a2 string
//   - _a3 string
//   - _a4 int
//   - _a5 *uuid.UUID
func (_e *MockUserReader_Expecter) SearchUsers(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}, _a5 interface{}) *MockUserReader_SearchUsers_Call {
	return &MockUserReader_SearchUsers_Call{Call: _e.mock.On("SearchUsers", _a0, _a1, _a2, _a3, _a4, _a5)}
}

func (_c *MockUserReader_SearchUsers_Call) Run(run func(_a0 context.Context, _a1 uuid.UUID, _a2 string, _a3 string, _a4 int, _a5 *uuid.UUID)) *MockUserReader_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(string), args[3].(string), args[4].(int), args[5].(*uuid.UUID))
	})
	return _c
}

func (_c *MockUserReader_SearchUsers_Call) Return(_a0 []*ent.User, _a1 string, _a2 bool, _a3 error) *MockUserReader_SearchUsers_Call {
	_c.Call.Return(_a0, _a1, _a2, _a3)
	return _c
}

func (_c *MockUserReader_SearchUsers_Call) RunAndReturn(run func(context.Context, uuid.UUID, string, string, int, *uuid.UUID) ([]*ent.User, string, bool, error)) *MockUserReader_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserReader creates a new instance of MockUserReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserReader {
	mock := &MockUserReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
