// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/messageoutbox"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageOutboxCreate is the builder for creating a MessageOutbox entity.
type MessageOutboxCreate struct {
	config
	mutation *MessageOutboxMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MessageOutboxCreate) SetCreatedAt(v time.Time) *MessageOutboxCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableCreatedAt(v *time.Time) *MessageOutboxCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MessageOutboxCreate) SetUpdatedAt(v time.Time) *MessageOutboxCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableUpdatedAt(v *time.Time) *MessageOutboxCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *MessageOutboxCreate) SetEventType(v string) *MessageOutboxCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetMessageID sets the "message_id" field.
func (_c *MessageOutboxCreate) SetMessageID(v uuid.UUID) *MessageOutboxCreate {
	_c.mutation.SetMessageID(v)
	return _c
}

// SetChatID sets the "chat_id" field.
func (_c *MessageOutboxCreate) SetChatID(v uuid.UUID) *MessageOutboxCreate {
	_c.mutation.SetChatID(v)
	return _c
}

// SetSenderID sets the "sender_id" field.
func (_c *MessageOutboxCreate) SetSenderID(v uuid.UUID) *MessageOutboxCreate {
	_c.mutation.SetSenderID(v)
	return _c
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableSenderID(v *uuid.UUID) *MessageOutboxCreate {
	if v != nil {
		_c.SetSenderID(*v)
	}
	return _c
}

// SetPayload sets the "payload" field.
func (_c *MessageOutboxCreate) SetPayload(v map[string]interface{}) *MessageOutboxCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetAttemptCount sets the "attempt_count" field.
func (_c *MessageOutboxCreate) SetAttemptCount(v int) *MessageOutboxCreate {
	_c.mutation.SetAttemptCount(v)
	return _c
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableAttemptCount(v *int) *MessageOutboxCreate {
	if v != nil {
		_c.SetAttemptCount(*v)
	}
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *MessageOutboxCreate) SetAvailableAt(v time.Time) *MessageOutboxCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableAvailableAt(v *time.Time) *MessageOutboxCreate {
	if v != nil {
		_c.SetAvailableAt(*v)
	}
	return _c
}

// SetLockedAt sets the "locked_at" field.
func (_c *MessageOutboxCreate) SetLockedAt(v time.Time) *MessageOutboxCreate {
	_c.mutation.SetLockedAt(v)
	return _c
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableLockedAt(v *time.Time) *MessageOutboxCreate {
	if v != nil {
		_c.SetLockedAt(*v)
	}
	return _c
}

// SetLockToken sets the "lock_token" field.
func (_c *MessageOutboxCreate) SetLockToken(v uuid.UUID) *MessageOutboxCreate {
	_c.mutation.SetLockToken(v)
	return _c
}

// SetNillableLockToken sets the "lock_token" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableLockToken(v *uuid.UUID) *MessageOutboxCreate {
	if v != nil {
		_c.SetLockToken(*v)
	}
	return _c
}

// SetProjectedAt sets the "projected_at" field.
func (_c *MessageOutboxCreate) SetProjectedAt(v time.Time) *MessageOutboxCreate {
	_c.mutation.SetProjectedAt(v)
	return _c
}

// SetNillableProjectedAt sets the "projected_at" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableProjectedAt(v *time.Time) *MessageOutboxCreate {
	if v != nil {
		_c.SetProjectedAt(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *MessageOutboxCreate) SetPublishedAt(v time.Time) *MessageOutboxCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillablePublishedAt(v *time.Time) *MessageOutboxCreate {
	if v != nil {
		_c.SetPublishedAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *MessageOutboxCreate) SetLastError(v string) *MessageOutboxCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableLastError(v *string) *MessageOutboxCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MessageOutboxCreate) SetID(v uuid.UUID) *MessageOutboxCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MessageOutboxCreate) SetNillableID(v *uuid.UUID) *MessageOutboxCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the MessageOutboxMutation object of the builder.
func (_c *MessageOutboxCreate) Mutation() *MessageOutboxMutation {
	return _c.mutation
}

// Save creates the MessageOutbox in the database.
func (_c *MessageOutboxCreate) Save(ctx context.Context) (*MessageOutbox, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MessageOutboxCreate) SaveX(ctx context.Context) *MessageOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageOutboxCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageOutboxCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MessageOutboxCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := messageoutbox.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := messageoutbox.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		v := messageoutbox.DefaultAttemptCount
		_c.mutation.SetAttemptCount(v)
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		v := messageoutbox.DefaultAvailableAt()
		_c.mutation.SetAvailableAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := messageoutbox.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MessageOutboxCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "MessageOutbox.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "MessageOutbox.updated_at"`)}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "MessageOutbox.event_type"`)}
	}
	if _, ok := _c.mutation.MessageID(); !ok {
		return &ValidationError{Name: "message_id", err: errors.New(`ent: missing required field "MessageOutbox.message_id"`)}
	}
	if _, ok := _c.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "MessageOutbox.chat_id"`)}
	}
	if _, ok := _c.mutation.AttemptCount(); !ok {
		return &ValidationError{Name: "attempt_count", err: errors.New(`ent: missing required field "MessageOutbox.attempt_count"`)}
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "MessageOutbox.available_at"`)}
	}
	return nil
}

func (_c *MessageOutboxCreate) sqlSave(ctx context.Context) (*MessageOutbox, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MessageOutboxCreate) createSpec() (*MessageOutbox, *sqlgraph.CreateSpec) {
	var (
		_node = &MessageOutbox{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(messageoutbox.Table, sqlgraph.NewFieldSpec(messageoutbox.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(messageoutbox.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(messageoutbox.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(messageoutbox.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.MessageID(); ok {
		_spec.SetField(messageoutbox.FieldMessageID, field.TypeUUID, value)
		_node.MessageID = value
	}
	if value, ok := _c.mutation.ChatID(); ok {
		_spec.SetField(messageoutbox.FieldChatID, field.TypeUUID, value)
		_node.ChatID = value
	}
	if value, ok := _c.mutation.SenderID(); ok {
		_spec.SetField(messageoutbox.FieldSenderID, field.TypeUUID, value)
		_node.SenderID = &value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(messageoutbox.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.AttemptCount(); ok {
		_spec.SetField(messageoutbox.FieldAttemptCount, field.TypeInt, value)
		_node.AttemptCount = value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(messageoutbox.FieldAvailableAt, field.TypeTime, value)
		_node.AvailableAt = value
	}
	if value, ok := _c.mutation.LockedAt(); ok {
		_spec.SetField(messageoutbox.FieldLockedAt, field.TypeTime, value)
		_node.LockedAt = &value
	}
	if value, ok := _c.mutation.LockToken(); ok {
		_spec.SetField(messageoutbox.FieldLockToken, field.TypeUUID, value)
		_node.LockToken = &value
	}
	if value, ok := _c.mutation.ProjectedAt(); ok {
		_spec.SetField(messageoutbox.FieldProjectedAt, field.TypeTime, value)
		_node.ProjectedAt = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(messageoutbox.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(messageoutbox.FieldLastError, field.TypeString, value)
		_node.LastError = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MessageOutbox.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageOutboxUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageOutboxCreate) OnConflict(opts ...sql.ConflictOption) *MessageOutboxUpsertOne {
	_c.conflict = opts
	return &MessageOutboxUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MessageOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageOutboxCreate) OnConflictColumns(columns ...string) *MessageOutboxUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageOutboxUpsertOne{
		create: _c,
	}
}

type (
	// MessageOutboxUpsertOne is the builder for "upsert"-ing
	//  one MessageOutbox node.
	MessageOutboxUpsertOne struct {
		create *MessageOutboxCreate
	}

	// MessageOutboxUpsert is the "OnConflict" setter.
	MessageOutboxUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageOutboxUpsert) SetUpdatedAt(v time.Time) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateUpdatedAt() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldUpdatedAt)
	return u
}

// SetEventType sets the "event_type" field.
func (u *MessageOutboxUpsert) SetEventType(v string) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldEventType, v)
	return u
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateEventType() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldEventType)
	return u
}

// SetMessageID sets the "message_id" field.
func (u *MessageOutboxUpsert) SetMessageID(v uuid.UUID) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldMessageID, v)
	return u
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateMessageID() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldMessageID)
	return u
}

// SetChatID sets the "chat_id" field.
func (u *MessageOutboxUpsert) SetChatID(v uuid.UUID) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldChatID, v)
	return u
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateChatID() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldChatID)
	return u
}

// SetSenderID sets the "sender_id" field.
func (u *MessageOutboxUpsert) SetSenderID(v uuid.UUID) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldSenderID, v)
	return u
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateSenderID() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldSenderID)
	return u
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *MessageOutboxUpsert) ClearSenderID() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldSenderID)
	return u
}

// SetPayload sets the "payload" field.
func (u *MessageOutboxUpsert) SetPayload(v map[string]interface{}) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdatePayload() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldPayload)
	return u
}

// ClearPayload clears the value of the "payload" field.
func (u *MessageOutboxUpsert) ClearPayload() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldPayload)
	return u
}

// SetAttemptCount sets the "attempt_count" field.
func (u *MessageOutboxUpsert) SetAttemptCount(v int) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldAttemptCount, v)
	return u
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateAttemptCount() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldAttemptCount)
	return u
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *MessageOutboxUpsert) AddAttemptCount(v int) *MessageOutboxUpsert {
	u.Add(messageoutbox.FieldAttemptCount, v)
	return u
}

// SetAvailableAt sets the "available_at" field.
func (u *MessageOutboxUpsert) SetAvailableAt(v time.Time) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldAvailableAt, v)
	return u
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateAvailableAt() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldAvailableAt)
	return u
}

// SetLockedAt sets the "locked_at" field.
func (u *MessageOutboxUpsert) SetLockedAt(v time.Time) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldLockedAt, v)
	return u
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateLockedAt() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldLockedAt)
	return u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *MessageOutboxUpsert) ClearLockedAt() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldLockedAt)
	return u
}

// SetLockToken sets the "lock_token" field.
func (u *MessageOutboxUpsert) SetLockToken(v uuid.UUID) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldLockToken, v)
	return u
}

// UpdateLockToken sets the "lock_token" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateLockToken() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldLockToken)
	return u
}

// ClearLockToken clears the value of the "lock_token" field.
func (u *MessageOutboxUpsert) ClearLockToken() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldLockToken)
	return u
}

// SetProjectedAt sets the "projected_at" field.
func (u *MessageOutboxUpsert) SetProjectedAt(v time.Time) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldProjectedAt, v)
	return u
}

// UpdateProjectedAt sets the "projected_at" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateProjectedAt() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldProjectedAt)
	return u
}

// ClearProjectedAt clears the value of the "projected_at" field.
func (u *MessageOutboxUpsert) ClearProjectedAt() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldProjectedAt)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *MessageOutboxUpsert) SetPublishedAt(v time.Time) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdatePublishedAt() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldPublishedAt)
	return u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *MessageOutboxUpsert) ClearPublishedAt() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldPublishedAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *MessageOutboxUpsert) SetLastError(v string) *MessageOutboxUpsert {
	u.Set(messageoutbox.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MessageOutboxUpsert) UpdateLastError() *MessageOutboxUpsert {
	u.SetExcluded(messageoutbox.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *MessageOutboxUpsert) ClearLastError() *MessageOutboxUpsert {
	u.SetNull(messageoutbox.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.MessageOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(messageoutbox.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MessageOutboxUpsertOne) UpdateNewValues() *MessageOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(messageoutbox.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(messageoutbox.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MessageOutbox.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MessageOutboxUpsertOne) Ignore() *MessageOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageOutboxUpsertOne) DoNothing() *MessageOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageOutboxCreate.OnConflict
// documentation for more info.
func (u *MessageOutboxUpsertOne) Update(set func(*MessageOutboxUpsert)) *MessageOutboxUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageOutboxUpsertOne) SetUpdatedAt(v time.Time) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateUpdatedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEventType sets the "event_type" field.
func (u *MessageOutboxUpsertOne) SetEventType(v string) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateEventType() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateEventType()
	})
}

// SetMessageID sets the "message_id" field.
func (u *MessageOutboxUpsertOne) SetMessageID(v uuid.UUID) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateMessageID() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateMessageID()
	})
}

// SetChatID sets the "chat_id" field.
func (u *MessageOutboxUpsertOne) SetChatID(v uuid.UUID) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateChatID() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateChatID()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *MessageOutboxUpsertOne) SetSenderID(v uuid.UUID) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateSenderID() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateSenderID()
	})
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *MessageOutboxUpsertOne) ClearSenderID() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearSenderID()
	})
}

// SetPayload sets the "payload" field.
func (u *MessageOutboxUpsertOne) SetPayload(v map[string]interface{}) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdatePayload() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *MessageOutboxUpsertOne) ClearPayload() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearPayload()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *MessageOutboxUpsertOne) SetAttemptCount(v int) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *MessageOutboxUpsertOne) AddAttemptCount(v int) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateAttemptCount() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *MessageOutboxUpsertOne) SetAvailableAt(v time.Time) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateAvailableAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *MessageOutboxUpsertOne) SetLockedAt(v time.Time) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateLockedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *MessageOutboxUpsertOne) ClearLockedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearLockedAt()
	})
}

// SetLockToken sets the "lock_token" field.
func (u *MessageOutboxUpsertOne) SetLockToken(v uuid.UUID) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetLockToken(v)
	})
}

// UpdateLockToken sets the "lock_token" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateLockToken() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateLockToken()
	})
}

// ClearLockToken clears the value of the "lock_token" field.
func (u *MessageOutboxUpsertOne) ClearLockToken() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearLockToken()
	})
}

// SetProjectedAt sets the "projected_at" field.
func (u *MessageOutboxUpsertOne) SetProjectedAt(v time.Time) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetProjectedAt(v)
	})
}

// UpdateProjectedAt sets the "projected_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateProjectedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateProjectedAt()
	})
}

// ClearProjectedAt clears the value of the "projected_at" field.
func (u *MessageOutboxUpsertOne) ClearProjectedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearProjectedAt()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *MessageOutboxUpsertOne) SetPublishedAt(v time.Time) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdatePublishedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *MessageOutboxUpsertOne) ClearPublishedAt() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearPublishedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *MessageOutboxUpsertOne) SetLastError(v string) *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MessageOutboxUpsertOne) UpdateLastError() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *MessageOutboxUpsertOne) ClearLastError() *MessageOutboxUpsertOne {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *MessageOutboxUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageOutboxCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageOutboxUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MessageOutboxUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MessageOutboxUpsertOne.ID is not supported by MySQL driver. Use MessageOutboxUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MessageOutboxUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MessageOutboxCreateBulk is the builder for creating many MessageOutbox entities in bulk.
type MessageOutboxCreateBulk struct {
	config
	err      error
	builders []*MessageOutboxCreate
	conflict []sql.ConflictOption
}

// Save creates the MessageOutbox entities in the database.
func (_c *MessageOutboxCreateBulk) Save(ctx context.Context) ([]*MessageOutbox, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*MessageOutbox, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageOutboxMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MessageOutboxCreateBulk) SaveX(ctx context.Context) []*MessageOutbox {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MessageOutboxCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MessageOutboxCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.MessageOutbox.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MessageOutboxUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MessageOutboxCreateBulk) OnConflict(opts ...sql.ConflictOption) *MessageOutboxUpsertBulk {
	_c.conflict = opts
	return &MessageOutboxUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.MessageOutbox.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MessageOutboxCreateBulk) OnConflictColumns(columns ...string) *MessageOutboxUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MessageOutboxUpsertBulk{
		create: _c,
	}
}

// MessageOutboxUpsertBulk is the builder for "upsert"-ing
// a bulk of MessageOutbox nodes.
type MessageOutboxUpsertBulk struct {
	create *MessageOutboxCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.MessageOutbox.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(messageoutbox.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MessageOutboxUpsertBulk) UpdateNewValues() *MessageOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(messageoutbox.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(messageoutbox.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.MessageOutbox.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MessageOutboxUpsertBulk) Ignore() *MessageOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MessageOutboxUpsertBulk) DoNothing() *MessageOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MessageOutboxCreateBulk.OnConflict
// documentation for more info.
func (u *MessageOutboxUpsertBulk) Update(set func(*MessageOutboxUpsert)) *MessageOutboxUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MessageOutboxUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MessageOutboxUpsertBulk) SetUpdatedAt(v time.Time) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateUpdatedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetEventType sets the "event_type" field.
func (u *MessageOutboxUpsertBulk) SetEventType(v string) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetEventType(v)
	})
}

// UpdateEventType sets the "event_type" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateEventType() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateEventType()
	})
}

// SetMessageID sets the "message_id" field.
func (u *MessageOutboxUpsertBulk) SetMessageID(v uuid.UUID) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetMessageID(v)
	})
}

// UpdateMessageID sets the "message_id" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateMessageID() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateMessageID()
	})
}

// SetChatID sets the "chat_id" field.
func (u *MessageOutboxUpsertBulk) SetChatID(v uuid.UUID) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetChatID(v)
	})
}

// UpdateChatID sets the "chat_id" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateChatID() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateChatID()
	})
}

// SetSenderID sets the "sender_id" field.
func (u *MessageOutboxUpsertBulk) SetSenderID(v uuid.UUID) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetSenderID(v)
	})
}

// UpdateSenderID sets the "sender_id" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateSenderID() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateSenderID()
	})
}

// ClearSenderID clears the value of the "sender_id" field.
func (u *MessageOutboxUpsertBulk) ClearSenderID() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearSenderID()
	})
}

// SetPayload sets the "payload" field.
func (u *MessageOutboxUpsertBulk) SetPayload(v map[string]interface{}) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdatePayload() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdatePayload()
	})
}

// ClearPayload clears the value of the "payload" field.
func (u *MessageOutboxUpsertBulk) ClearPayload() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearPayload()
	})
}

// SetAttemptCount sets the "attempt_count" field.
func (u *MessageOutboxUpsertBulk) SetAttemptCount(v int) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetAttemptCount(v)
	})
}

// AddAttemptCount adds v to the "attempt_count" field.
func (u *MessageOutboxUpsertBulk) AddAttemptCount(v int) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.AddAttemptCount(v)
	})
}

// UpdateAttemptCount sets the "attempt_count" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateAttemptCount() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateAttemptCount()
	})
}

// SetAvailableAt sets the "available_at" field.
func (u *MessageOutboxUpsertBulk) SetAvailableAt(v time.Time) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetAvailableAt(v)
	})
}

// UpdateAvailableAt sets the "available_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateAvailableAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateAvailableAt()
	})
}

// SetLockedAt sets the "locked_at" field.
func (u *MessageOutboxUpsertBulk) SetLockedAt(v time.Time) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetLockedAt(v)
	})
}

// UpdateLockedAt sets the "locked_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateLockedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateLockedAt()
	})
}

// ClearLockedAt clears the value of the "locked_at" field.
func (u *MessageOutboxUpsertBulk) ClearLockedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearLockedAt()
	})
}

// SetLockToken sets the "lock_token" field.
func (u *MessageOutboxUpsertBulk) SetLockToken(v uuid.UUID) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetLockToken(v)
	})
}

// UpdateLockToken sets the "lock_token" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateLockToken() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateLockToken()
	})
}

// ClearLockToken clears the value of the "lock_token" field.
func (u *MessageOutboxUpsertBulk) ClearLockToken() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearLockToken()
	})
}

// SetProjectedAt sets the "projected_at" field.
func (u *MessageOutboxUpsertBulk) SetProjectedAt(v time.Time) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetProjectedAt(v)
	})
}

// UpdateProjectedAt sets the "projected_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateProjectedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateProjectedAt()
	})
}

// ClearProjectedAt clears the value of the "projected_at" field.
func (u *MessageOutboxUpsertBulk) ClearProjectedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearProjectedAt()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *MessageOutboxUpsertBulk) SetPublishedAt(v time.Time) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdatePublishedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdatePublishedAt()
	})
}

// ClearPublishedAt clears the value of the "published_at" field.
func (u *MessageOutboxUpsertBulk) ClearPublishedAt() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearPublishedAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *MessageOutboxUpsertBulk) SetLastError(v string) *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *MessageOutboxUpsertBulk) UpdateLastError() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *MessageOutboxUpsertBulk) ClearLastError() *MessageOutboxUpsertBulk {
	return u.Update(func(s *MessageOutboxUpsert) {
		s.ClearLastError()
	})
}

// Exec executes the query.
func (u *MessageOutboxUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MessageOutboxCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MessageOutboxCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MessageOutboxUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
