// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/messageoutbox"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// MessageOutbox is the model entity for the MessageOutbox schema.
type MessageOutbox struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// EventType holds the value of the "event_type" field.
	EventType string `json:"event_type,omitempty"`
	// MessageID holds the value of the "message_id" field.
	MessageID uuid.UUID `json:"message_id,omitempty"`
	// ChatID holds the value of the "chat_id" field.
	ChatID uuid.UUID `json:"chat_id,omitempty"`
	// SenderID holds the value of the "sender_id" field.
	SenderID *uuid.UUID `json:"sender_id,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// AttemptCount holds the value of the "attempt_count" field.
	AttemptCount int `json:"attempt_count,omitempty"`
	// AvailableAt holds the value of the "available_at" field.
	AvailableAt time.Time `json:"available_at,omitempty"`
	// LockedAt holds the value of the "locked_at" field.
	LockedAt *time.Time `json:"locked_at,omitempty"`
	// LockToken holds the value of the "lock_token" field.
	LockToken *uuid.UUID `json:"lock_token,omitempty"`
	// ProjectedAt holds the value of the "projected_at" field.
	ProjectedAt *time.Time `json:"projected_at,omitempty"`
	// PublishedAt holds the value of the "published_at" field.
	PublishedAt *time.Time `json:"published_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError    *string `json:"last_error,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MessageOutbox) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case messageoutbox.FieldSenderID, messageoutbox.FieldLockToken:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case messageoutbox.FieldPayload:
			values[i] = new([]byte)
		case messageoutbox.FieldAttemptCount:
			values[i] = new(sql.NullInt64)
		case messageoutbox.FieldEventType, messageoutbox.FieldLastError:
			values[i] = new(sql.NullString)
		case messageoutbox.FieldCreatedAt, messageoutbox.FieldUpdatedAt, messageoutbox.FieldAvailableAt, messageoutbox.FieldLockedAt, messageoutbox.FieldProjectedAt, messageoutbox.FieldPublishedAt:
			values[i] = new(sql.NullTime)
		case messageoutbox.FieldID, messageoutbox.FieldMessageID, messageoutbox.FieldChatID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MessageOutbox fields.
func (_m *MessageOutbox) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case messageoutbox.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case messageoutbox.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case messageoutbox.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case messageoutbox.FieldEventType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field event_type", values[i])
			} else if value.Valid {
				_m.EventType = value.String
			}
		case messageoutbox.FieldMessageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field message_id", values[i])
			} else if value != nil {
				_m.MessageID = *value
			}
		case messageoutbox.FieldChatID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field chat_id", values[i])
			} else if value != nil {
				_m.ChatID = *value
			}
		case messageoutbox.FieldSenderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field sender_id", values[i])
			} else if value.Valid {
				_m.SenderID = new(uuid.UUID)
				*_m.SenderID = *value.S.(*uuid.UUID)
			}
		case messageoutbox.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case messageoutbox.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case messageoutbox.FieldAvailableAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field available_at", values[i])
			} else if value.Valid {
				_m.AvailableAt = value.Time
			}
		case messageoutbox.FieldLockedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field locked_at", values[i])
			} else if value.Valid {
				_m.LockedAt = new(time.Time)
				*_m.LockedAt = value.Time
			}
		case messageoutbox.FieldLockToken:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field lock_token", values[i])
			} else if value.Valid {
				_m.LockToken = new(uuid.UUID)
				*_m.LockToken = *value.S.(*uuid.UUID)
			}
		case messageoutbox.FieldProjectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field projected_at", values[i])
			} else if value.Valid {
				_m.ProjectedAt = new(time.Time)
				*_m.ProjectedAt = value.Time
			}
		case messageoutbox.FieldPublishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field published_at", values[i])
			} else if value.Valid {
				_m.PublishedAt = new(time.Time)
				*_m.PublishedAt = value.Time
			}
		case messageoutbox.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MessageOutbox.
// This includes values selected through modifiers, order, etc.
func (_m *MessageOutbox) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this MessageOutbox.
// Note that you need to call MessageOutbox.Unwrap() before calling this method if this MessageOutbox
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *MessageOutbox) Update() *MessageOutboxUpdateOne {
	return NewMessageOutboxClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the MessageOutbox entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *MessageOutbox) Unwrap() *MessageOutbox {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: MessageOutbox is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *MessageOutbox) String() string {
	var builder strings.Builder
	builder.WriteString("MessageOutbox(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("event_type=")
	builder.WriteString(_m.EventType)
	builder.WriteString(", ")
	builder.WriteString("message_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.MessageID))
	builder.WriteString(", ")
	builder.WriteString("chat_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatID))
	builder.WriteString(", ")
	if v := _m.SenderID; v != nil {
		builder.WriteString("sender_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("available_at=")
	builder.WriteString(_m.AvailableAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.LockedAt; v != nil {
		builder.WriteString("locked_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LockToken; v != nil {
		builder.WriteString("lock_token=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProjectedAt; v != nil {
		builder.WriteString("projected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.PublishedAt; v != nil {
		builder.WriteString("published_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// MessageOutboxes is a parsable slice of MessageOutbox.
type MessageOutboxes []*MessageOutbox
