// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/messageoutbox"
	"AtoiTalkAPI/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MessageOutboxDelete is the builder for deleting a MessageOutbox entity.
type MessageOutboxDelete struct {
	config
	hooks    []Hook
	mutation *MessageOutboxMutation
}

// Where appends a list predicates to the MessageOutboxDelete builder.
func (_d *MessageOutboxDelete) Where(ps ...predicate.MessageOutbox) *MessageOutboxDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *MessageOutboxDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MessageOutboxDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *MessageOutboxDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(messageoutbox.Table, sqlgraph.NewFieldSpec(messageoutbox.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// MessageOutboxDeleteOne is the builder for deleting a single MessageOutbox entity.
type MessageOutboxDeleteOne struct {
	_d *MessageOutboxDelete
}

// Where appends a list predicates to the MessageOutboxDelete builder.
func (_d *MessageOutboxDeleteOne) Where(ps ...predicate.MessageOutbox) *MessageOutboxDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *MessageOutboxDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messageoutbox.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *MessageOutboxDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
