// Code generated by ent, DO NOT EDIT.

package ent

import (
	"AtoiTalkAPI/ent/messageoutbox"
	"AtoiTalkAPI/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MessageOutboxUpdate is the builder for updating MessageOutbox entities.
type MessageOutboxUpdate struct {
	config
	hooks     []Hook
	mutation  *MessageOutboxMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MessageOutboxUpdate builder.
func (_u *MessageOutboxUpdate) Where(ps ...predicate.MessageOutbox) *MessageOutboxUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageOutboxUpdate) SetUpdatedAt(v time.Time) *MessageOutboxUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *MessageOutboxUpdate) SetEventType(v string) *MessageOutboxUpdate {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableEventType(v *string) *MessageOutboxUpdate {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageOutboxUpdate) SetMessageID(v uuid.UUID) *MessageOutboxUpdate {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableMessageID(v *uuid.UUID) *MessageOutboxUpdate {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *MessageOutboxUpdate) SetChatID(v uuid.UUID) *MessageOutboxUpdate {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableChatID(v *uuid.UUID) *MessageOutboxUpdate {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *MessageOutboxUpdate) SetSenderID(v uuid.UUID) *MessageOutboxUpdate {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableSenderID(v *uuid.UUID) *MessageOutboxUpdate {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *MessageOutboxUpdate) ClearSenderID() *MessageOutboxUpdate {
	_u.mutation.ClearSenderID()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MessageOutboxUpdate) SetPayload(v map[string]interface{}) *MessageOutboxUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MessageOutboxUpdate) ClearPayload() *MessageOutboxUpdate {
	_u.mutation.ClearPayload()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *MessageOutboxUpdate) SetAttemptCount(v int) *MessageOutboxUpdate {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableAttemptCount(v *int) *MessageOutboxUpdate {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *MessageOutboxUpdate) AddAttemptCount(v int) *MessageOutboxUpdate {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetAvailableAt sets the "available_at" field.
func (_u *MessageOutboxUpdate) SetAvailableAt(v time.Time) *MessageOutboxUpdate {
	_u.mutation.SetAvailableAt(v)
	return _u
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableAvailableAt(v *time.Time) *MessageOutboxUpdate {
	if v != nil {
		_u.SetAvailableAt(*v)
	}
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *MessageOutboxUpdate) SetLockedAt(v time.Time) *MessageOutboxUpdate {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableLockedAt(v *time.Time) *MessageOutboxUpdate {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *MessageOutboxUpdate) ClearLockedAt() *MessageOutboxUpdate {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLockToken sets the "lock_token" field.
func (_u *MessageOutboxUpdate) SetLockToken(v uuid.UUID) *MessageOutboxUpdate {
	_u.mutation.SetLockToken(v)
	return _u
}

// SetNillableLockToken sets the "lock_token" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableLockToken(v *uuid.UUID) *MessageOutboxUpdate {
	if v != nil {
		_u.SetLockToken(*v)
	}
	return _u
}

// ClearLockToken clears the value of the "lock_token" field.
func (_u *MessageOutboxUpdate) ClearLockToken() *MessageOutboxUpdate {
	_u.mutation.ClearLockToken()
	return _u
}

// SetProjectedAt sets the "projected_at" field.
func (_u *MessageOutboxUpdate) SetProjectedAt(v time.Time) *MessageOutboxUpdate {
	_u.mutation.SetProjectedAt(v)
	return _u
}

// SetNillableProjectedAt sets the "projected_at" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableProjectedAt(v *time.Time) *MessageOutboxUpdate {
	if v != nil {
		_u.SetProjectedAt(*v)
	}
	return _u
}

// ClearProjectedAt clears the value of the "projected_at" field.
func (_u *MessageOutboxUpdate) ClearProjectedAt() *MessageOutboxUpdate {
	_u.mutation.ClearProjectedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MessageOutboxUpdate) SetPublishedAt(v time.Time) *MessageOutboxUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillablePublishedAt(v *time.Time) *MessageOutboxUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MessageOutboxUpdate) ClearPublishedAt() *MessageOutboxUpdate {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *MessageOutboxUpdate) SetLastError(v string) *MessageOutboxUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *MessageOutboxUpdate) SetNillableLastError(v *string) *MessageOutboxUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *MessageOutboxUpdate) ClearLastError() *MessageOutboxUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the MessageOutboxMutation object of the builder.
func (_u *MessageOutboxUpdate) Mutation() *MessageOutboxMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MessageOutboxUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageOutboxUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MessageOutboxUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageOutboxUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageOutboxUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := messageoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MessageOutboxUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MessageOutboxUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MessageOutboxUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(messageoutbox.Table, messageoutbox.Columns, sqlgraph.NewFieldSpec(messageoutbox.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(messageoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(messageoutbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(messageoutbox.FieldMessageID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(messageoutbox.FieldChatID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(messageoutbox.FieldSenderID, field.TypeUUID, value)
	}
	if _u.mutation.SenderIDCleared() {
		_spec.ClearField(messageoutbox.FieldSenderID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(messageoutbox.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(messageoutbox.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(messageoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(messageoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AvailableAt(); ok {
		_spec.SetField(messageoutbox.FieldAvailableAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(messageoutbox.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(messageoutbox.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockToken(); ok {
		_spec.SetField(messageoutbox.FieldLockToken, field.TypeUUID, value)
	}
	if _u.mutation.LockTokenCleared() {
		_spec.ClearField(messageoutbox.FieldLockToken, field.TypeUUID)
	}
	if value, ok := _u.mutation.ProjectedAt(); ok {
		_spec.SetField(messageoutbox.FieldProjectedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectedAtCleared() {
		_spec.ClearField(messageoutbox.FieldProjectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(messageoutbox.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(messageoutbox.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(messageoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(messageoutbox.FieldLastError, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messageoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MessageOutboxUpdateOne is the builder for updating a single MessageOutbox entity.
type MessageOutboxUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MessageOutboxMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MessageOutboxUpdateOne) SetUpdatedAt(v time.Time) *MessageOutboxUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetEventType sets the "event_type" field.
func (_u *MessageOutboxUpdateOne) SetEventType(v string) *MessageOutboxUpdateOne {
	_u.mutation.SetEventType(v)
	return _u
}

// SetNillableEventType sets the "event_type" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableEventType(v *string) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetEventType(*v)
	}
	return _u
}

// SetMessageID sets the "message_id" field.
func (_u *MessageOutboxUpdateOne) SetMessageID(v uuid.UUID) *MessageOutboxUpdateOne {
	_u.mutation.SetMessageID(v)
	return _u
}

// SetNillableMessageID sets the "message_id" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableMessageID(v *uuid.UUID) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetMessageID(*v)
	}
	return _u
}

// SetChatID sets the "chat_id" field.
func (_u *MessageOutboxUpdateOne) SetChatID(v uuid.UUID) *MessageOutboxUpdateOne {
	_u.mutation.SetChatID(v)
	return _u
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableChatID(v *uuid.UUID) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetChatID(*v)
	}
	return _u
}

// SetSenderID sets the "sender_id" field.
func (_u *MessageOutboxUpdateOne) SetSenderID(v uuid.UUID) *MessageOutboxUpdateOne {
	_u.mutation.SetSenderID(v)
	return _u
}

// SetNillableSenderID sets the "sender_id" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableSenderID(v *uuid.UUID) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetSenderID(*v)
	}
	return _u
}

// ClearSenderID clears the value of the "sender_id" field.
func (_u *MessageOutboxUpdateOne) ClearSenderID() *MessageOutboxUpdateOne {
	_u.mutation.ClearSenderID()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *MessageOutboxUpdateOne) SetPayload(v map[string]interface{}) *MessageOutboxUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// ClearPayload clears the value of the "payload" field.
func (_u *MessageOutboxUpdateOne) ClearPayload() *MessageOutboxUpdateOne {
	_u.mutation.ClearPayload()
	return _u
}

// SetAttemptCount sets the "attempt_count" field.
func (_u *MessageOutboxUpdateOne) SetAttemptCount(v int) *MessageOutboxUpdateOne {
	_u.mutation.ResetAttemptCount()
	_u.mutation.SetAttemptCount(v)
	return _u
}

// SetNillableAttemptCount sets the "attempt_count" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableAttemptCount(v *int) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetAttemptCount(*v)
	}
	return _u
}

// AddAttemptCount adds value to the "attempt_count" field.
func (_u *MessageOutboxUpdateOne) AddAttemptCount(v int) *MessageOutboxUpdateOne {
	_u.mutation.AddAttemptCount(v)
	return _u
}

// SetAvailableAt sets the "available_at" field.
func (_u *MessageOutboxUpdateOne) SetAvailableAt(v time.Time) *MessageOutboxUpdateOne {
	_u.mutation.SetAvailableAt(v)
	return _u
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableAvailableAt(v *time.Time) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetAvailableAt(*v)
	}
	return _u
}

// SetLockedAt sets the "locked_at" field.
func (_u *MessageOutboxUpdateOne) SetLockedAt(v time.Time) *MessageOutboxUpdateOne {
	_u.mutation.SetLockedAt(v)
	return _u
}

// SetNillableLockedAt sets the "locked_at" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableLockedAt(v *time.Time) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetLockedAt(*v)
	}
	return _u
}

// ClearLockedAt clears the value of the "locked_at" field.
func (_u *MessageOutboxUpdateOne) ClearLockedAt() *MessageOutboxUpdateOne {
	_u.mutation.ClearLockedAt()
	return _u
}

// SetLockToken sets the "lock_token" field.
func (_u *MessageOutboxUpdateOne) SetLockToken(v uuid.UUID) *MessageOutboxUpdateOne {
	_u.mutation.SetLockToken(v)
	return _u
}

// SetNillableLockToken sets the "lock_token" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableLockToken(v *uuid.UUID) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetLockToken(*v)
	}
	return _u
}

// ClearLockToken clears the value of the "lock_token" field.
func (_u *MessageOutboxUpdateOne) ClearLockToken() *MessageOutboxUpdateOne {
	_u.mutation.ClearLockToken()
	return _u
}

// SetProjectedAt sets the "projected_at" field.
func (_u *MessageOutboxUpdateOne) SetProjectedAt(v time.Time) *MessageOutboxUpdateOne {
	_u.mutation.SetProjectedAt(v)
	return _u
}

// SetNillableProjectedAt sets the "projected_at" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableProjectedAt(v *time.Time) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetProjectedAt(*v)
	}
	return _u
}

// ClearProjectedAt clears the value of the "projected_at" field.
func (_u *MessageOutboxUpdateOne) ClearProjectedAt() *MessageOutboxUpdateOne {
	_u.mutation.ClearProjectedAt()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *MessageOutboxUpdateOne) SetPublishedAt(v time.Time) *MessageOutboxUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillablePublishedAt(v *time.Time) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// ClearPublishedAt clears the value of the "published_at" field.
func (_u *MessageOutboxUpdateOne) ClearPublishedAt() *MessageOutboxUpdateOne {
	_u.mutation.ClearPublishedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *MessageOutboxUpdateOne) SetLastError(v string) *MessageOutboxUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *MessageOutboxUpdateOne) SetNillableLastError(v *string) *MessageOutboxUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *MessageOutboxUpdateOne) ClearLastError() *MessageOutboxUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the MessageOutboxMutation object of the builder.
func (_u *MessageOutboxUpdateOne) Mutation() *MessageOutboxMutation {
	return _u.mutation
}

// Where appends a list predicates to the MessageOutboxUpdate builder.
func (_u *MessageOutboxUpdateOne) Where(ps ...predicate.MessageOutbox) *MessageOutboxUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MessageOutboxUpdateOne) Select(field string, fields ...string) *MessageOutboxUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated MessageOutbox entity.
func (_u *MessageOutboxUpdateOne) Save(ctx context.Context) (*MessageOutbox, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MessageOutboxUpdateOne) SaveX(ctx context.Context) *MessageOutbox {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MessageOutboxUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MessageOutboxUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MessageOutboxUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := messageoutbox.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *MessageOutboxUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MessageOutboxUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *MessageOutboxUpdateOne) sqlSave(ctx context.Context) (_node *MessageOutbox, err error) {
	_spec := sqlgraph.NewUpdateSpec(messageoutbox.Table, messageoutbox.Columns, sqlgraph.NewFieldSpec(messageoutbox.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MessageOutbox.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messageoutbox.FieldID)
		for _, f := range fields {
			if !messageoutbox.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != messageoutbox.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(messageoutbox.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EventType(); ok {
		_spec.SetField(messageoutbox.FieldEventType, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageID(); ok {
		_spec.SetField(messageoutbox.FieldMessageID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ChatID(); ok {
		_spec.SetField(messageoutbox.FieldChatID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.SenderID(); ok {
		_spec.SetField(messageoutbox.FieldSenderID, field.TypeUUID, value)
	}
	if _u.mutation.SenderIDCleared() {
		_spec.ClearField(messageoutbox.FieldSenderID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(messageoutbox.FieldPayload, field.TypeJSON, value)
	}
	if _u.mutation.PayloadCleared() {
		_spec.ClearField(messageoutbox.FieldPayload, field.TypeJSON)
	}
	if value, ok := _u.mutation.AttemptCount(); ok {
		_spec.SetField(messageoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAttemptCount(); ok {
		_spec.AddField(messageoutbox.FieldAttemptCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AvailableAt(); ok {
		_spec.SetField(messageoutbox.FieldAvailableAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LockedAt(); ok {
		_spec.SetField(messageoutbox.FieldLockedAt, field.TypeTime, value)
	}
	if _u.mutation.LockedAtCleared() {
		_spec.ClearField(messageoutbox.FieldLockedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LockToken(); ok {
		_spec.SetField(messageoutbox.FieldLockToken, field.TypeUUID, value)
	}
	if _u.mutation.LockTokenCleared() {
		_spec.ClearField(messageoutbox.FieldLockToken, field.TypeUUID)
	}
	if value, ok := _u.mutation.ProjectedAt(); ok {
		_spec.SetField(messageoutbox.FieldProjectedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectedAtCleared() {
		_spec.ClearField(messageoutbox.FieldProjectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(messageoutbox.FieldPublishedAt, field.TypeTime, value)
	}
	if _u.mutation.PublishedAtCleared() {
		_spec.ClearField(messageoutbox.FieldPublishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(messageoutbox.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(messageoutbox.FieldLastError, field.TypeString)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &MessageOutbox{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{messageoutbox.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
