// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockCaptchaVerifier is an autogenerated mock type for the CaptchaVerifier type
type MockCaptchaVerifier struct {
	mock.Mock
}

type MockCaptchaVerifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCaptchaVerifier) EXPECT() *MockCaptchaVerifier_Expecter {
	return &MockCaptchaVerifier_Expecter{mock: &_m.Mock}
}

// Verify provides a mock function with given fields: _a0, _a1
func (_m *MockCaptchaVerifier) Verify(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Verify")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCaptchaVerifier_Verify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Verify'
type MockCaptchaVerifier_Verify_Call struct {
	*mock.Call
}

// Verify is a helper method to define mock.On call
//   - _a0 string
//   - _a1 string
func (_e *MockCaptchaVerifier_Expecter) Verify(_a0 interface{}, _a1 interface{}) *MockCaptchaVerifier_Verify_Call {
	return &MockCaptchaVerifier_Verify_Call{Call: _e.mock.On("Verify", _a0, _a1)}
}

func (_c *MockCaptchaVerifier_Verify_Call) Run(run func(_a0 string, _a1 string)) *MockCaptchaVerifier_Verify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCaptchaVerifier_Verify_Call) Return(_a0 error) *MockCaptchaVerifier_Verify_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCaptchaVerifier_Verify_Call) RunAndReturn(run func(string, string) error) *MockCaptchaVerifier_Verify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCaptchaVerifier creates a new instance of MockCaptchaVerifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCaptchaVerifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCaptchaVerifier {
	mock := &MockCaptchaVerifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
