// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockPublicURLGenerator is an autogenerated mock type for the PublicURLGenerator type
type MockPublicURLGenerator struct {
	mock.Mock
}

type MockPublicURLGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublicURLGenerator) EXPECT() *MockPublicURLGenerator_Expecter {
	return &MockPublicURLGenerator_Expecter{mock: &_m.Mock}
}

// GetPublicURL provides a mock function with given fields: _a0
func (_m *MockPublicURLGenerator) GetPublicURL(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPublicURLGenerator_GetPublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicURL'
type MockPublicURLGenerator_GetPublicURL_Call struct {
	*mock.Call
}

// GetPublicURL is a helper method to define mock.On call
//   - _a0 string
func (_e *MockPublicURLGenerator_Expecter) GetPublicURL(_a0 interface{}) *MockPublicURLGenerator_GetPublicURL_Call {
	return &MockPublicURLGenerator_GetPublicURL_Call{Call: _e.mock.On("GetPublicURL", _a0)}
}

func (_c *MockPublicURLGenerator_GetPublicURL_Call) Run(run func(_a0 string)) *MockPublicURLGenerator_GetPublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockPublicURLGenerator_GetPublicURL_Call) Return(_a0 string) *MockPublicURLGenerator_GetPublicURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublicURLGenerator_GetPublicURL_Call) RunAndReturn(run func(string) string) *MockPublicURLGenerator_GetPublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublicURLGenerator creates a new instance of MockPublicURLGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublicURLGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublicURLGenerator {
	mock := &MockPublicURLGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
