// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockRedisStore is an autogenerated mock type for the RedisStore type
type MockRedisStore struct {
	mock.Mock
}

type MockRedisStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisStore) EXPECT() *MockRedisStore_Expecter {
	return &MockRedisStore_Expecter{mock: &_m.Mock}
}

// Del provides a mock function with given fields: _a0, _a1
func (_m *MockRedisStore) Del(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Del")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisStore_Del_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Del'
type MockRedisStore_Del_Call struct {
	*mock.Call
}

// Del is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRedisStore_Expecter) Del(_a0 interface{}, _a1 interface{}) *MockRedisStore_Del_Call {
	return &MockRedisStore_Del_Call{Call: _e.mock.On("Del", _a0, _a1)}
}

func (_c *MockRedisStore_Del_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRedisStore_Del_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisStore_Del_Call) Return(_a0 error) *MockRedisStore_Del_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisStore_Del_Call) RunAndReturn(run func(context.Context, string) error) *MockRedisStore_Del_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: _a0, _a1
func (_m *MockRedisStore) Get(_a0 context.Context, _a1 string) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRedisStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockRedisStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
func (_e *MockRedisStore_Expecter) Get(_a0 interface{}, _a1 interface{}) *MockRedisStore_Get_Call {
	return &MockRedisStore_Get_Call{Call: _e.mock.On("Get", _a0, _a1)}
}

func (_c *MockRedisStore_Get_Call) Run(run func(_a0 context.Context, _a1 string)) *MockRedisStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRedisStore_Get_Call) Return(_a0 string, _a1 error) *MockRedisStore_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRedisStore_Get_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockRedisStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockRedisStore) Set(_a0 context.Context, _a1 string, _a2 interface{}, _a3 time.Duration) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, time.Duration) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRedisStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockRedisStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 interface{}
//   - _a3 time.Duration
func (_e *MockRedisStore_Expecter) Set(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockRedisStore_Set_Call {
	return &MockRedisStore_Set_Call{Call: _e.mock.On("Set", _a0, _a1, _a2, _a3)}
}

func (_c *MockRedisStore_Set_Call) Run(run func(_a0 context.Context, _a1 string, _a2 interface{}, _a3 time.Duration)) *MockRedisStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockRedisStore_Set_Call) Return(_a0 error) *MockRedisStore_Set_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRedisStore_Set_Call) RunAndReturn(run func(context.Context, string, interface{}, time.Duration) error) *MockRedisStore_Set_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRedisStore creates a new instance of MockRedisStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisStore {
	mock := &MockRedisStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
