// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockURLGenerator is an autogenerated mock type for the URLGenerator type
type MockURLGenerator struct {
	mock.Mock
}

type MockURLGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLGenerator) EXPECT() *MockURLGenerator_Expecter {
	return &MockURLGenerator_Expecter{mock: &_m.Mock}
}

// GetPresignedURL provides a mock function with given fields: _a0, _a1
func (_m *MockURLGenerator) GetPresignedURL(_a0 string, _a1 time.Duration) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetPresignedURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLGenerator_GetPresignedURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPresignedURL'
type MockURLGenerator_GetPresignedURL_Call struct {
	*mock.Call
}

// GetPresignedURL is a helper method to define mock.On call
//   - _a0 string
//   - _a1 time.Duration
func (_e *MockURLGenerator_Expecter) GetPresignedURL(_a0 interface{}, _a1 interface{}) *MockURLGenerator_GetPresignedURL_Call {
	return &MockURLGenerator_GetPresignedURL_Call{Call: _e.mock.On("GetPresignedURL", _a0, _a1)}
}

func (_c *MockURLGenerator_GetPresignedURL_Call) Run(run func(_a0 string, _a1 time.Duration)) *MockURLGenerator_GetPresignedURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockURLGenerator_GetPresignedURL_Call) Return(_a0 string, _a1 error) *MockURLGenerator_GetPresignedURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLGenerator_GetPresignedURL_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *MockURLGenerator_GetPresignedURL_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublicURL provides a mock function with given fields: _a0
func (_m *MockURLGenerator) GetPublicURL(_a0 string) string {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetPublicURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockURLGenerator_GetPublicURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublicURL'
type MockURLGenerator_GetPublicURL_Call struct {
	*mock.Call
}

// GetPublicURL is a helper method to define mock.On call
//   - _a0 string
func (_e *MockURLGenerator_Expecter) GetPublicURL(_a0 interface{}) *MockURLGenerator_GetPublicURL_Call {
	return &MockURLGenerator_GetPublicURL_Call{Call: _e.mock.On("GetPublicURL", _a0)}
}

func (_c *MockURLGenerator_GetPublicURL_Call) Run(run func(_a0 string)) *MockURLGenerator_GetPublicURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLGenerator_GetPublicURL_Call) Return(_a0 string) *MockURLGenerator_GetPublicURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLGenerator_GetPublicURL_Call) RunAndReturn(run func(string) string) *MockURLGenerator_GetPublicURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLGenerator creates a new instance of MockURLGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLGenerator {
	mock := &MockURLGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
