// Code generated by ent, DO NOT EDIT.

package messageoutbox

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the messageoutbox type in the database.
	Label = "message_outbox"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldMessageID holds the string denoting the message_id field in the database.
	FieldMessageID = "message_id"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldSenderID holds the string denoting the sender_id field in the database.
	FieldSenderID = "sender_id"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// FieldAttemptCount holds the string denoting the attempt_count field in the database.
	FieldAttemptCount = "attempt_count"
	// FieldAvailableAt holds the string denoting the available_at field in the database.
	FieldAvailableAt = "available_at"
	// FieldLockedAt holds the string denoting the locked_at field in the database.
	FieldLockedAt = "locked_at"
	// FieldLockToken holds the string denoting the lock_token field in the database.
	FieldLockToken = "lock_token"
	// FieldProjectedAt holds the string denoting the projected_at field in the database.
	FieldProjectedAt = "projected_at"
	// FieldPublishedAt holds the string denoting the published_at field in the database.
	FieldPublishedAt = "published_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// Table holds the table name of the messageoutbox in the database.
	Table = "message_outboxes"
)

// Columns holds all SQL columns for messageoutbox fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldEventType,
	FieldMessageID,
	FieldChatID,
	FieldSenderID,
	FieldPayload,
	FieldAttemptCount,
	FieldAvailableAt,
	FieldLockedAt,
	FieldLockToken,
	FieldProjectedAt,
	FieldPublishedAt,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAttemptCount holds the default value on creation for the "attempt_count" field.
	DefaultAttemptCount int
	// DefaultAvailableAt holds the default value on creation for the "available_at" field.
	DefaultAvailableAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the MessageOutbox queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByMessageID orders the results by the message_id field.
func ByMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageID, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// BySenderID orders the results by the sender_id field.
func BySenderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSenderID, opts...).ToFunc()
}

// ByAttemptCount orders the results by the attempt_count field.
func ByAttemptCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptCount, opts...).ToFunc()
}

// ByAvailableAt orders the results by the available_at field.
func ByAvailableAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailableAt, opts...).ToFunc()
}

// ByLockedAt orders the results by the locked_at field.
func ByLockedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockedAt, opts...).ToFunc()
}

// ByLockToken orders the results by the lock_token field.
func ByLockToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLockToken, opts...).ToFunc()
}

// ByProjectedAt orders the results by the projected_at field.
func ByProjectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProjectedAt, opts...).ToFunc()
}

// ByPublishedAt orders the results by the published_at field.
func ByPublishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublishedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}
