// Code generated by ent, DO NOT EDIT.

package messageoutbox

import (
	"AtoiTalkAPI/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldEventType, v))
}

// MessageID applies equality check predicate on the "message_id" field. It's identical to MessageIDEQ.
func MessageID(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldMessageID, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldChatID, v))
}

// SenderID applies equality check predicate on the "sender_id" field. It's identical to SenderIDEQ.
func SenderID(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldSenderID, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldAttemptCount, v))
}

// AvailableAt applies equality check predicate on the "available_at" field. It's identical to AvailableAtEQ.
func AvailableAt(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldAvailableAt, v))
}

// LockedAt applies equality check predicate on the "locked_at" field. It's identical to LockedAtEQ.
func LockedAt(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldLockedAt, v))
}

// LockToken applies equality check predicate on the "lock_token" field. It's identical to LockTokenEQ.
func LockToken(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldLockToken, v))
}

// ProjectedAt applies equality check predicate on the "projected_at" field. It's identical to ProjectedAtEQ.
func ProjectedAt(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldProjectedAt, v))
}

// PublishedAt applies equality check predicate on the "published_at" field. It's identical to PublishedAtEQ.
func PublishedAt(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldPublishedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldUpdatedAt, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldContainsFold(FieldEventType, v))
}

// MessageIDEQ applies the EQ predicate on the "message_id" field.
func MessageIDEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldMessageID, v))
}

// MessageIDNEQ applies the NEQ predicate on the "message_id" field.
func MessageIDNEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldMessageID, v))
}

// MessageIDIn applies the In predicate on the "message_id" field.
func MessageIDIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldMessageID, vs...))
}

// MessageIDNotIn applies the NotIn predicate on the "message_id" field.
func MessageIDNotIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldMessageID, vs...))
}

// MessageIDGT applies the GT predicate on the "message_id" field.
func MessageIDGT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldMessageID, v))
}

// MessageIDGTE applies the GTE predicate on the "message_id" field.
func MessageIDGTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldMessageID, v))
}

// MessageIDLT applies the LT predicate on the "message_id" field.
func MessageIDLT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldMessageID, v))
}

// MessageIDLTE applies the LTE predicate on the "message_id" field.
func MessageIDLTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldMessageID, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldChatID, v))
}

// SenderIDEQ applies the EQ predicate on the "sender_id" field.
func SenderIDEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldSenderID, v))
}

// SenderIDNEQ applies the NEQ predicate on the "sender_id" field.
func SenderIDNEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldSenderID, v))
}

// SenderIDIn applies the In predicate on the "sender_id" field.
func SenderIDIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldSenderID, vs...))
}

// SenderIDNotIn applies the NotIn predicate on the "sender_id" field.
func SenderIDNotIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldSenderID, vs...))
}

// SenderIDGT applies the GT predicate on the "sender_id" field.
func SenderIDGT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldSenderID, v))
}

// SenderIDGTE applies the GTE predicate on the "sender_id" field.
func SenderIDGTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldSenderID, v))
}

// SenderIDLT applies the LT predicate on the "sender_id" field.
func SenderIDLT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldSenderID, v))
}

// SenderIDLTE applies the LTE predicate on the "sender_id" field.
func SenderIDLTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldSenderID, v))
}

// SenderIDIsNil applies the IsNil predicate on the "sender_id" field.
func SenderIDIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldSenderID))
}

// SenderIDNotNil applies the NotNil predicate on the "sender_id" field.
func SenderIDNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldSenderID))
}

// PayloadIsNil applies the IsNil predicate on the "payload" field.
func PayloadIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldPayload))
}

// PayloadNotNil applies the NotNil predicate on the "payload" field.
func PayloadNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldPayload))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldAttemptCount, v))
}

// AvailableAtEQ applies the EQ predicate on the "available_at" field.
func AvailableAtEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldAvailableAt, v))
}

// AvailableAtNEQ applies the NEQ predicate on the "available_at" field.
func AvailableAtNEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldAvailableAt, v))
}

// AvailableAtIn applies the In predicate on the "available_at" field.
func AvailableAtIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldAvailableAt, vs...))
}

// AvailableAtNotIn applies the NotIn predicate on the "available_at" field.
func AvailableAtNotIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldAvailableAt, vs...))
}

// AvailableAtGT applies the GT predicate on the "available_at" field.
func AvailableAtGT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldAvailableAt, v))
}

// AvailableAtGTE applies the GTE predicate on the "available_at" field.
func AvailableAtGTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldAvailableAt, v))
}

// AvailableAtLT applies the LT predicate on the "available_at" field.
func AvailableAtLT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldAvailableAt, v))
}

// AvailableAtLTE applies the LTE predicate on the "available_at" field.
func AvailableAtLTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldAvailableAt, v))
}

// LockedAtEQ applies the EQ predicate on the "locked_at" field.
func LockedAtEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldLockedAt, v))
}

// LockedAtNEQ applies the NEQ predicate on the "locked_at" field.
func LockedAtNEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldLockedAt, v))
}

// LockedAtIn applies the In predicate on the "locked_at" field.
func LockedAtIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldLockedAt, vs...))
}

// LockedAtNotIn applies the NotIn predicate on the "locked_at" field.
func LockedAtNotIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldLockedAt, vs...))
}

// LockedAtGT applies the GT predicate on the "locked_at" field.
func LockedAtGT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldLockedAt, v))
}

// LockedAtGTE applies the GTE predicate on the "locked_at" field.
func LockedAtGTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldLockedAt, v))
}

// LockedAtLT applies the LT predicate on the "locked_at" field.
func LockedAtLT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldLockedAt, v))
}

// LockedAtLTE applies the LTE predicate on the "locked_at" field.
func LockedAtLTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldLockedAt, v))
}

// LockedAtIsNil applies the IsNil predicate on the "locked_at" field.
func LockedAtIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldLockedAt))
}

// LockedAtNotNil applies the NotNil predicate on the "locked_at" field.
func LockedAtNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldLockedAt))
}

// LockTokenEQ applies the EQ predicate on the "lock_token" field.
func LockTokenEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldLockToken, v))
}

// LockTokenNEQ applies the NEQ predicate on the "lock_token" field.
func LockTokenNEQ(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldLockToken, v))
}

// LockTokenIn applies the In predicate on the "lock_token" field.
func LockTokenIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldLockToken, vs...))
}

// LockTokenNotIn applies the NotIn predicate on the "lock_token" field.
func LockTokenNotIn(vs ...uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldLockToken, vs...))
}

// LockTokenGT applies the GT predicate on the "lock_token" field.
func LockTokenGT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldLockToken, v))
}

// LockTokenGTE applies the GTE predicate on the "lock_token" field.
func LockTokenGTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldLockToken, v))
}

// LockTokenLT applies the LT predicate on the "lock_token" field.
func LockTokenLT(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldLockToken, v))
}

// LockTokenLTE applies the LTE predicate on the "lock_token" field.
func LockTokenLTE(v uuid.UUID) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldLockToken, v))
}

// LockTokenIsNil applies the IsNil predicate on the "lock_token" field.
func LockTokenIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldLockToken))
}

// LockTokenNotNil applies the NotNil predicate on the "lock_token" field.
func LockTokenNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldLockToken))
}

// ProjectedAtEQ applies the EQ predicate on the "projected_at" field.
func ProjectedAtEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldProjectedAt, v))
}

// ProjectedAtNEQ applies the NEQ predicate on the "projected_at" field.
func ProjectedAtNEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldProjectedAt, v))
}

// ProjectedAtIn applies the In predicate on the "projected_at" field.
func ProjectedAtIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldProjectedAt, vs...))
}

// ProjectedAtNotIn applies the NotIn predicate on the "projected_at" field.
func ProjectedAtNotIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldProjectedAt, vs...))
}

// ProjectedAtGT applies the GT predicate on the "projected_at" field.
func ProjectedAtGT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldProjectedAt, v))
}

// ProjectedAtGTE applies the GTE predicate on the "projected_at" field.
func ProjectedAtGTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldProjectedAt, v))
}

// ProjectedAtLT applies the LT predicate on the "projected_at" field.
func ProjectedAtLT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldProjectedAt, v))
}

// ProjectedAtLTE applies the LTE predicate on the "projected_at" field.
func ProjectedAtLTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldProjectedAt, v))
}

// ProjectedAtIsNil applies the IsNil predicate on the "projected_at" field.
func ProjectedAtIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldProjectedAt))
}

// ProjectedAtNotNil applies the NotNil predicate on the "projected_at" field.
func ProjectedAtNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldProjectedAt))
}

// PublishedAtEQ applies the EQ predicate on the "published_at" field.
func PublishedAtEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldPublishedAt, v))
}

// PublishedAtNEQ applies the NEQ predicate on the "published_at" field.
func PublishedAtNEQ(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldPublishedAt, v))
}

// PublishedAtIn applies the In predicate on the "published_at" field.
func PublishedAtIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldPublishedAt, vs...))
}

// PublishedAtNotIn applies the NotIn predicate on the "published_at" field.
func PublishedAtNotIn(vs ...time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldPublishedAt, vs...))
}

// PublishedAtGT applies the GT predicate on the "published_at" field.
func PublishedAtGT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldPublishedAt, v))
}

// PublishedAtGTE applies the GTE predicate on the "published_at" field.
func PublishedAtGTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldPublishedAt, v))
}

// PublishedAtLT applies the LT predicate on the "published_at" field.
func PublishedAtLT(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldPublishedAt, v))
}

// PublishedAtLTE applies the LTE predicate on the "published_at" field.
func PublishedAtLTE(v time.Time) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldPublishedAt, v))
}

// PublishedAtIsNil applies the IsNil predicate on the "published_at" field.
func PublishedAtIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldPublishedAt))
}

// PublishedAtNotNil applies the NotNil predicate on the "published_at" field.
func PublishedAtNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldPublishedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MessageOutbox) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MessageOutbox) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MessageOutbox) predicate.MessageOutbox {
	return predicate.MessageOutbox(sql.NotPredicates(p))
}
